### ISSUE TITLE
An exception is raised when running demo.py

### ISSUE THREAD

**Issue by happycoding1996** [eragonruan/text-detection-ctpn#115]
#When I wanted to run ./ctpn/demo.py, an error happenedd. 

#The information is as follows

Loading network VGGnet_test...  Restoring from checkpoints/VGGnet_fast_rcnn_iter_50000.ckpt... Traceback (most recent call last):
  File "./ctpn/demo.py", line 88, in <module>
    raise Exception('Check your pretrained {:s}'.format(ckpt.model_checkpoint_path))
Exception: Check your pretrained checkpoints/VGGnet_fast_rcnn_iter_50000.ckpt
root@docker-10-0-1-7:/cephfs/group/youtu/gaia/zhuotaotian/east/text-detection-ctpn-master/checkpoints# ls
VGGnet_fast_rcnn_iter_50000.ckpt.data-00000-of-00001  VGGnet_fast_rcnn_iter_50000.ckpt.index  VGGnet_fast_rcnn_iter_50000.ckpt.meta  checkpoint

#The checkpoint files do exist in this directory. Can anyone tells me how I can solve this problem?

**Comment by tianzhuotao** [comment]
@eragonruan

**Comment by eragonruan** [comment]
@tianzhuotao this is caused by different version of tensorflow. see [here](https://github.com/eragonruan/text-detection-ctpn/issues/1) for more detail

**Comment by LQNew** [comment]
@tianzhuotao  how did you fix?? i'm meeting the same problem,and i can't fix it..

**Comment by tianzhuotao** [comment]
@LQNew  Installing another version of TF can help.

**Comment by LQNew** [comment]
@tianzhuotao  You meant installing tf 1.1.0?

**Comment by Mary2333** [comment]
@LQNew Hi, I also met the problem today, I tried install tensorflow 1.1 and 1.3, but they are didn't work, at last I install tensorflow 1.2, the issue is solved. Good luck!
