### ISSUE TITLE
Whether the texts can be separated with different detecting windows when they are far away from each other?

### ISSUE THREAD

**Issue by YCG09** [eragonruan/text-detection-ctpn#125]
there is an example: 

![_20180403145524](https://user-images.githubusercontent.com/9940376/38234174-a21dcfdc-374f-11e8-8d0b-2350e90d264d.png)

**Comment by eragonruan** [comment]
@YCG09 try lower the [MAX_HORIZONTAL_GAP](https://github.com/eragonruan/text-detection-ctpn/blob/b94c3af3d5105b5a9ff4d4a00edf92b2d55ee4cf/lib/text_connector/text_connect_cfg.py#L8)

**Comment by YCG09** [comment]
thanks!
