### ISSUE TITLE
fatal error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by xuewenyuan** [eragonruan/text-detection-ctpn#13]
When I try to build nms implement and run `./make.sh`,  there was an error happened:  
`bbox.c:517:31: fatal error: numpy/arrayobject.h: No such file or directory`  
It seems a path problem. But where should I modify the path. 
The path of numpy in my enviroment is:  
'/usr/local/lib/python2.7/dist-packages/numpy/core/include'

**Comment by xuewenyuan** [comment]
According to [this page](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory), I have solved the problem by modifying some codes in `./lib/utils/setup.py` as follows:  
```
ext_modules = [
    Extension(
        "utils.bbox",
        ["bbox.pyx"]
	),
    Extension(
        "utils.nms",
        ["nms.pyx"],
        include_dirs=[np.get_include()]
    ),]

setup(ext_modules=cythonize(ext_modules),include_dirs=[np.get_include()])
```
So I closed this issue.

**Comment by eragonruan** [comment]
@xuewenyuan Thanks for the contribute.

**Comment by xxllp** [comment]
为啥我这么改了后还是报错找不到呢
