### ISSUE TITLE
How to export model for Tensorflow Serving?

### ISSUE THREAD

**Issue by hiepph** [eragonruan/text-detection-ctpn#134]
Follow some tutorials of exporting model for Tensorflow Serving, I've come up below trial:

```
cfg_from_file('ctpn/text.yml')
config = tf.ConfigProto(allow_soft_placement=True)
with tf.Session(config=config) as sess:
        net = get_network("VGGnet_test")

        saver = tf.train.Saver()
        try:
            ckpt = tf.train.get_checkpoint_state(cfg.TEST.checkpoints_path)
            saver.restore(sess, ckpt.model_checkpoint_path)
        except:
            raise 'Missing pre-trained model: {}'.format(ckpt.model_checkpoint_path)

       # The main export trial is here
       #############################
        export_path = os.path.join(
            tf.compat.as_bytes('/tmp/ctpn'),
            tf.compat.as_bytes(str(1)))
        builder = tf.saved_model.builder.SavedModelBuilder(export_path)

        freezing_graph = sess.graph
        prediction_signature = tf.saved_model.signature_def_utils.predict_signature_def(
            inputs={'input': freezing_graph.get_tensor_by_name('Placeholder:0')},
            outputs={'output': freezing_graph.get_tensor_by_name('Placeholder_1:0')}
        )

        builder.add_meta_graph_and_variables(
            sess,
            [tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: prediction_signature
            },
            clear_devices=True)

        builder.save()
        print('[INFO] Export SavedModel into {}'.format(export_path))
        #############################
```

With output of `freezing_graph` is:

```
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_2:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape_1:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
```

After I got `/tmp/ctpn/1` exported model, I try to load into Tensorflow Serving server:

```
tensorflow_model_server --port=9000 --model_name=ctpn --model_base_path=/tmp/ctpn
```

But it came up an error:

```
Loading servable: {name: detector version: 1} failed: Not found: Op type not registered 'PyFunc' in binary running on [...]. Make sure the Op and Kernel are registered in the binary running in this process.
```

So there are 2 questions:

+ Am I right about the inputs (`Placeholder:0`) and the outputs (`Placeholder_1:0`) of `prediction_signature`
+ Where do I miss `PyFunc`?

**Comment by eragonruan** [comment]
@hiepph I have release the pb file. enjoy it

**Comment by hurricanedjp** [comment]
@eragonruan I load the pb file as demo.pb did, and export save_model for tf serving but I can't get variables.
so I use ckpt file to do same thing,here is my code:
`
from __future__ import print_function
import tensorflow as tf
import numpy as np
import os, sys, cv2
from tensorflow.python.platform import gfile
import glob
import shutil

dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(dir_path, '..'))

from lib.networks.factory import get_network
from lib.fast_rcnn.config import cfg, cfg_from_file
from lib.fast_rcnn.test import test_ctpn
from lib.utils.timer import Timer
from lib.text_connector.detectors import TextDetector
from lib.text_connector.text_connect_cfg import Config as TextLineCfg

dir_path = os.path.dirname(os.path.realpath(__file__))


def export():
  cfg_from_file(os.path.join(dir_path, 'text.yml'))
  config = tf.ConfigProto(allow_soft_placement=True)
  sess = tf.Session(config=config)
  # with gfile.FastGFile('../data/ctpn.pb', 'rb') as f:
  #   graph_def = tf.GraphDef()
  #   graph_def.ParseFromString(f.read())
  #   sess.graph.as_default()
  #   tf.import_graph_def(graph_def, name='')
  # sess.run(tf.global_variables_initializer())

  net = get_network("VGGnet_test")
  print(('Loading network {:s}... '.format("VGGnet_test")), end=' ')
  saver = tf.train.Saver()
  try:
    ckpt_path = os.path.abspath(os.path.join(dir_path, cfg.TEST.checkpoints_path))
    ckpt = tf.train.get_checkpoint_state(ckpt_path)
    print('Restoring from {}...'.format(ckpt.model_checkpoint_path), end=' ')
    saver.restore(sess, ckpt.model_checkpoint_path)
    print('done')
  except:
    raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
  print(' done.')

  input_img = sess.graph.get_tensor_by_name('Placeholder:0')
  output_cls_prob = sess.graph.get_tensor_by_name('Reshape_2:0')
  output_box_pred = sess.graph.get_tensor_by_name('rpn_bbox_pred/Reshape_1:0')

  builder = tf.saved_model.builder.SavedModelBuilder('./export/1')

  imageplaceholder_info = tf.saved_model.utils.build_tensor_info(input_img)
  cls_prob_info = tf.saved_model.utils.build_tensor_info(output_cls_prob)
  box_pred_info = tf.saved_model.utils.build_tensor_info(output_box_pred)
  prediction_signature = (
    tf.saved_model.signature_def_utils.build_signature_def(
      inputs={
        'image': imageplaceholder_info
      },
      outputs={
        'output_cls_prob': cls_prob_info,
        'output_box_pred': box_pred_info
      },
      method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
    )
  )
  init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
  builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING],
       signature_def_map={'ctpn_recs_predict': prediction_signature}, legacy_init_op=init_op)
  builder.save()


if __name__ == '__main__':
  export()

`
But it also came up the error:
`Not found: Op type not registered 'PyFunc' in binary running on`

Please help me, how can I fix this

**Comment by hiepph** [comment]
I met the same problem with yours. Turn out that TF Serving (which written in C++) doesn't support PyFunc yet (which written in Python). You can see the issue here https://github.com/tensorflow/serving/issues/54

**Comment by hiepph** [comment]
Temporarily for production, you can use the pb file released by @eragonruan. It's pretty fast (2x speed) as my experiment.

**Comment by hurricanedjp** [comment]
@hiepph I know the pyfunc reason, but I wrote the export code refer to the generate_pb.py offered by @eragonruan and the error also occurs. By the way, I can't use pb.file directly, because I have a pipeline 
 with other models which has been successfully deployed on tensorflow serving

**Comment by hiepph** [comment]
I also have a successfully deployed system with Tensorflow Serving. And I know it's very inconsistent to use a mix of TF Serving and PB in a system.

But it is possible to do this combination, a temporary solution if you don't mind the strange mix:

```
# Boot up Tensorflow session for CTPN and load pb file
cfg_from_file('text.yml')

config = tf.ConfigProto(allow_soft_placement=True)
ctpn_sess = tf.Session(config=config)
with ctpn_sess.as_default():
    # Load pb graph
    with tf.gfile.FastGFile('models/ctpn.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        ctpn_sess.graph.as_default()
        tf.import_graph_def(graph_def, name='')
    ctpn_sess.run(tf.global_variables_initializer())

# Load your image here
img = cv2.imread('my-image.png')

# Query CTPN
boxes = query_pb(ctpn_sess, cfg, img) # function implemented below

# Now with coordinate boxes, you can save as an image or do whatever
# and then query your Tensorflow Serving
```

```
def query_pb(sess, cfg, img):
    """Args:
        sess: tensorflow session
        cfg: CTPN config
        img: numpy array image

   Returns:
       A list of detected bounding boxes,
        each bounding box have followed coordinates: [(xmin, ymin), (xmax, ymax)]
            (xmin, ymin) -------------
                 |                    |
             ---------------- (xmax, ymax)
    """
    # Specify input/output
    input_img  = sess.graph.get_tensor_by_name('Placeholder:0')
    output_cls_box = sess.graph.get_tensor_by_name('Reshape_2:0')
    output_box_pred = sess.graph.get_tensor_by_name('rpn_bbox_pred/Reshape_1:0')

    img, scale = resize_im(img, scale=TextLineCfg.SCALE, max_scale=TextLineCfg.MAX_SCALE)
    blobs, im_scales = _get_blobs(img, None)
    if cfg.TEST.HAS_RPN:
        im_blob = blobs['data']
        blobs['im_info'] = np.array([[im_blob.shape[1], im_blob.shape[2], im_scales[0]]],
                                    dtype=np.float32)
        cls_prob, box_pred = sess.run([output_cls_box, output_box_pred],
                                      feed_dict={input_img: blobs['data']})
        rois, _ = proposal_layer(cls_prob, box_pred, blobs['im_info'],
                                 'TEST', anchor_scales=cfg.ANCHOR_SCALES)

        scores = rois[:, 0]
        boxes = rois[:, 1:5] / im_scales[0]

        textdetector = TextDetector()
        boxes = textdetector.detect(boxes, scores[:, np.newaxis], img.shape[:2])

        # Convert boxes to bouding rectangles
        rects = []
        for box in boxes:
            min_x = min(int(box[0]/scale), int(box[2]/scale), int(box[4]/scale), int(box[6]/scale))
            min_y = min(int(box[1]/scale), int(box[3]/scale), int(box[5]/scale), int(box[7]/scale))
            max_x = max(int(box[0]/scale), int(box[2]/scale), int(box[4]/scale), int(box[6]/scale))
            max_y = max(int(box[1]/scale), int(box[3]/scale), int(box[5]/scale), int(box[7]/scale))

            rects.append([(min_x, min_y), (max_x, max_y)])

        return rects
```

**Comment by hurricanedjp** [comment]
@hiepph actually, I have tested two files. In my case, there is not much difference between pb file and ckpt file in testing time.  The times are all about 6 seconds, which are too slow for me.

**Comment by hiepph** [comment]
Really? ~ 6 seconds for ckpt and ~ 3 seconds for pb file as my experiment.

**Comment by hurricanedjp** [comment]
Yes, but I run the test code in cpu mode, and test one image. I haven't tested on the GPU yet.

**Comment by hurricanedjp** [comment]
@hiepph I have tested on the GPU, in my case, the test time are all about 4.4 seconds, which are also too slow

**Comment by seanlong** [comment]
@hurricanedjp you should exclude the py_func wrapped "proposal_layer_py" layer before generating your saved model.

**Comment by MrOCR** [comment]
@seanlong how to exclude the py_func wrapped "proposal_layer_py" layer?

**Comment by amit2319** [comment]
@hurricanedjp did you got it working? If yes can you describe it.

**Comment by amit2319** [comment]
@MrOCR  I resolved it. Just remove the 

`  
(self.feed('rpn_cls_prob_reshape', 'rpn_bbox_pred', 'im_info')
.proposal_layer(_feat_stride, anchor_scales, 'TEST', name='rois'))`

from _text-detection-ctpn/lib/networks/VGGnet_test.py_

It will exclude the proposal_layer_py layer.

**Comment by hcnhatnam** [comment]
> Yes, but I run the test code in cpu mode, and test one image. I haven't tested on the GPU yet.
I have the same problem

**Comment by hcnhatnam** [comment]
> @hiepph actually, I have tested two files. In my case, there is not much difference between pb file and ckpt file in testing time. The times are all about 6 seconds, which are too slow for me.

@hiepph  @hurricanedjp 
I have the same problem.

**Comment by kspook** [comment]
can anybody make curl statement?  
how can I test tensorflow serving?

**Comment by kspook** [comment]
I got malformed error at POSTSMAN.

================= input===========
POST : http://52.231.31.230:9001/v1/models/ctpn
Headers

cache-control       no-cache
content-type        application/json
Body

{
   "signature_name": "ctpn_recs_predict",
  "inputs": {
       "input": {"b64": <b64 >
   }
}

==========output (error) ==============
{
   "error": "Malformed request: POST /v1/models/ctpn"
}

**Comment by kspook** [comment]
I had problem for exporting on linux/GPU like this:
"Attempting to use uninitialized value conv1_1/biases_1"

but it works fine on Windows/GPU.
can any know how to solve this error?

=========. details of error ========
Tensor("Placeholder_1:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3_1:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3_1:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_5:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_5:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_3:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob_1:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_5:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape_3:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)
Loading network VGGnet_test...  <tensorflow.python.training.saver.Saver object at 0x7f95361afeb8>
Traceback (most recent call last):
  File "/home/kspook/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/kspook/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/home/kspook/anaconda3/envs/py36/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/kspook/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value conv1_1/biases_1
         [[Node: save_1/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save_1/ShardedFilename, save_1/SaveV2/tensor_names, save_1/SaveV2/shape_and_slices, conv1_1/biases_1, conv1_1/weights_1, conv1_2/biases_1, conv1_2/weights_1, conv2_1/biases_1, conv2_1/weights_1, conv2_2/biases_1, conv2_2/weights_1, conv3_1/biases_1, conv3_1/weights_1, conv3_2/biases_1, conv3_2/weights_1, conv3_3/biases_1, conv3_3/weights_1, conv4_1/biases_1, conv4_1/weights_1, conv4_2/biases_1, conv4_2/weights_1, conv4_3/biases_1, conv4_3/weights_1, conv5_1/biases_1, conv5_1/weights_1, conv5_2/biases_1, conv5_2/weights_1, conv5_3/biases_1, conv5_3/weights_1, lstm_o/biases_1, lstm_o/bidirectional_rnn/bw/lstm_cell/biases, lstm_o/bidirectional_rnn/bw/lstm_cell/weights, lstm_o/bidirectional_rnn/fw/lstm_cell/biases, lstm_o/bidirectional_rnn/fw/lstm_cell/weights, lstm_o/weights_1, rpn_bbox_pred/biases_1, rpn_bbox_pred/weights_1, rpn_cls_score/biases_1, rpn_cls_score/weights_1, rpn_conv/3x3/biases_1, rpn_conv/3x3/weights_1)]]

During handling of the above exception, another exception occurred:

**Comment by kspook** [comment]
I have another question . 

I made a curl script based on advice, https://github.com/tensorflow/serving/issues/994#issuecomment-410165268
However, I got an malformed error with curl script.
Can anyone tell me the reason?

================= input===========
curl -X POST   http://localhost:9001/v1/models/ctpn   -d '{
  "signature_name": "ctpn_recs_predict",
  "inputs": {
        "image": { "b64": "$(base64 /home/kspook/text-detection-ctpn/data/demo/006.jpg)" }
  }
}'

==========output (error) ==============
{
"error": "Malformed request: POST /v1/models/ctpn"
}

**Comment by kspook** [comment]
I made a script to input float. But, I have the same error as  "Object is the expected type : float".

the output is as follows:
....
[\n 0.054901961237192157,\n 0.054901961237192157,\n 0.054901961237192157\n ],\n [\n 0.05098039284348488,\n 0.05098039284348488,\n 0.05098039284348488\n ],\n [\n 0.04313725605607033,\n 0.05098039284348488,\n 0.05098039284348488\n ],\n [\n 0.03921568766236305,\n 0.0470588244497776,\n 0.0470588244497776\n ],\n [\n 0.03921568766236305,\n 0.0470588244497776,\n 0.0470588244497776\n ],\n [\n 0.03921568766236305,\n 0.0470588244497776,\n 0.0470588244497776\n ]\n ]\n ]\n }\n} Type: Object is not of expected type: float" }


import cv2
import numpy as np
import os
import base64
import json
import requests


URL="http://localhost:9001/v1/models/ctpn:predict"
headers = {"content-type": "application/json"}
 
image = cv2.imread("/home/kspook/text-detection-ctpn/data/demo/006.jpg", cv2.IMREAD_COLOR)
image = image.astype(np.float32) / 255
img_flt = image_as_float()
image = img_flt.tolist()

body = {
    "signature_name": "ctpn_recs_predict",
    "inputs": [
              {"image": { "b64": image }}
              #{"image": { "b64": image_content }}
              #{"image": { "b64": "$(base64 /home/kspook/text-detection-ctpn/data/demo/006.jpg)" }}
    ]
}
r = requests.post(URL, data=json.dumps(body), headers = headers)
print(r.text)

**Comment by ajinkya933** [comment]
> @eragonruan I load the pb file as demo.pb did, and export save_model for tf serving but I can't get variables file only save_model.pb.
> so I use ckpt file to do same thing,here is my code:
> 
> ```python
> from __future__ import print_function
> import tensorflow as tf
> import numpy as np
> import os, sys, cv2
> from tensorflow.python.platform import gfile
> import glob
> import shutil
> 
> dir_path = os.path.dirname(os.path.realpath(__file__))
> sys.path.append(os.path.join(dir_path, '..'))
> 
> from lib.networks.factory import get_network
> from lib.fast_rcnn.config import cfg, cfg_from_file
> from lib.fast_rcnn.test import test_ctpn
> from lib.utils.timer import Timer
> from lib.text_connector.detectors import TextDetector
> from lib.text_connector.text_connect_cfg import Config as TextLineCfg
> 
> dir_path = os.path.dirname(os.path.realpath(__file__))
> 
> 
> def export():
>   cfg_from_file(os.path.join(dir_path, 'text.yml'))
>   config = tf.ConfigProto(allow_soft_placement=True)
>   sess = tf.Session(config=config)
>   # with gfile.FastGFile('../data/ctpn.pb', 'rb') as f:
>   #   graph_def = tf.GraphDef()
>   #   graph_def.ParseFromString(f.read())
>   #   sess.graph.as_default()
>   #   tf.import_graph_def(graph_def, name='')
>   # sess.run(tf.global_variables_initializer())
> 
>   net = get_network("VGGnet_test")
>   print(('Loading network {:s}... '.format("VGGnet_test")), end=' ')
>   saver = tf.train.Saver()
>   try:
>     ckpt_path = os.path.abspath(os.path.join(dir_path, cfg.TEST.checkpoints_path))
>     ckpt = tf.train.get_checkpoint_state(ckpt_path)
>     print('Restoring from {}...'.format(ckpt.model_checkpoint_path), end=' ')
>     saver.restore(sess, ckpt.model_checkpoint_path)
>     print('done')
>   except:
>     raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
>   print(' done.')
> 
>   input_img = sess.graph.get_tensor_by_name('Placeholder:0')
>   output_cls_prob = sess.graph.get_tensor_by_name('Reshape_2:0')
>   output_box_pred = sess.graph.get_tensor_by_name('rpn_bbox_pred/Reshape_1:0')
> 
>   builder = tf.saved_model.builder.SavedModelBuilder('./export/1')
> 
>   imageplaceholder_info = tf.saved_model.utils.build_tensor_info(input_img)
>   cls_prob_info = tf.saved_model.utils.build_tensor_info(output_cls_prob)
>   box_pred_info = tf.saved_model.utils.build_tensor_info(output_box_pred)
>   prediction_signature = (
>     tf.saved_model.signature_def_utils.build_signature_def(
>       inputs={
>         'image': imageplaceholder_info
>       },
>       outputs={
>         'output_cls_prob': cls_prob_info,
>         'output_box_pred': box_pred_info
>       },
>       method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
>     )
>   )
>   init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
>   builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING],
>        signature_def_map={'ctpn_recs_predict': prediction_signature}, legacy_init_op=init_op)
>   builder.save()
> 
> 
> if __name__ == '__main__':
>   export()
> ```
> 
> Using ckpt file can get variables files and save_model.pb file, But when it runs also came up the error:
> 
> `Not found: Op type not registered 'PyFunc' in binary running on`
> 
> Please help me, how can I fix this

Using your code I exported the model to pb file. But turns out I am getting the same issue you got on docker: Not found: Op type not registered 'PyFunc' in binary running on 750da59b05de. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by ajinkya933** [comment]
> @mrocr I resolved it. Just remove the
> 
> ` (self.feed('rpn_cls_prob_reshape', 'rpn_bbox_pred', 'im_info') .proposal_layer(_feat_stride, anchor_scales, 'TEST', name='rois'))`
> 
> from _text-detection-ctpn/lib/networks/VGGnet_test.py_
> 
> It will exclude the proposal_layer_py layer.

this answer removed the above error and the server is started now I want to know how do you send image to tf server and how to get bounding box responses ?

**Comment by ajinkya933** [comment]
> I also have a successfully deployed system with Tensorflow Serving. And I know it's very inconsistent to use a mix of TF Serving and PB in a system.
> 
> But it is possible to do this combination, a temporary solution if you don't mind the strange mix:
> 
> ```
> # Boot up Tensorflow session for CTPN and load pb file
> cfg_from_file('text.yml')
> 
> config = tf.ConfigProto(allow_soft_placement=True)
> ctpn_sess = tf.Session(config=config)
> with ctpn_sess.as_default():
>     # Load pb graph
>     with tf.gfile.FastGFile('models/ctpn.pb', 'rb') as f:
>         graph_def = tf.GraphDef()
>         graph_def.ParseFromString(f.read())
>         ctpn_sess.graph.as_default()
>         tf.import_graph_def(graph_def, name='')
>     ctpn_sess.run(tf.global_variables_initializer())
> 
> # Load your image here
> img = cv2.imread('my-image.png')
> 
> # Query CTPN
> boxes = query_pb(ctpn_sess, cfg, img) # function implemented below
> 
> # Now with coordinate boxes, you can save as an image or do whatever
> # and then query your Tensorflow Serving
> ```
> 
> ```
> def query_pb(sess, cfg, img):
>     """Args:
>         sess: tensorflow session
>         cfg: CTPN config
>         img: numpy array image
> 
>    Returns:
>        A list of detected bounding boxes,
>         each bounding box have followed coordinates: [(xmin, ymin), (xmax, ymax)]
>             (xmin, ymin) -------------
>                  |                    |
>              ---------------- (xmax, ymax)
>     """
>     # Specify input/output
>     input_img  = sess.graph.get_tensor_by_name('Placeholder:0')
>     output_cls_box = sess.graph.get_tensor_by_name('Reshape_2:0')
>     output_box_pred = sess.graph.get_tensor_by_name('rpn_bbox_pred/Reshape_1:0')
> 
>     img, scale = resize_im(img, scale=TextLineCfg.SCALE, max_scale=TextLineCfg.MAX_SCALE)
>     blobs, im_scales = _get_blobs(img, None)
>     if cfg.TEST.HAS_RPN:
>         im_blob = blobs['data']
>         blobs['im_info'] = np.array([[im_blob.shape[1], im_blob.shape[2], im_scales[0]]],
>                                     dtype=np.float32)
>         cls_prob, box_pred = sess.run([output_cls_box, output_box_pred],
>                                       feed_dict={input_img: blobs['data']})
>         rois, _ = proposal_layer(cls_prob, box_pred, blobs['im_info'],
>                                  'TEST', anchor_scales=cfg.ANCHOR_SCALES)
> 
>         scores = rois[:, 0]
>         boxes = rois[:, 1:5] / im_scales[0]
> 
>         textdetector = TextDetector()
>         boxes = textdetector.detect(boxes, scores[:, np.newaxis], img.shape[:2])
> 
>         # Convert boxes to bouding rectangles
>         rects = []
>         for box in boxes:
>             min_x = min(int(box[0]/scale), int(box[2]/scale), int(box[4]/scale), int(box[6]/scale))
>             min_y = min(int(box[1]/scale), int(box[3]/scale), int(box[5]/scale), int(box[7]/scale))
>             max_x = max(int(box[0]/scale), int(box[2]/scale), int(box[4]/scale), int(box[6]/scale))
>             max_y = max(int(box[1]/scale), int(box[3]/scale), int(box[5]/scale), int(box[7]/scale))
> 
>             rects.append([(min_x, min_y), (max_x, max_y)])
> 
>         return rects
> ```

@hiepph how did you implement this in tensorflow serving, did you use REST Api or grpc ?
