### ISSUE TITLE
use resnet   instead of  vggnet 

### ISSUE THREAD

**Issue by lxx1884896** [eragonruan/text-detection-ctpn#136]

**Comment by eragonruan** [comment]
sorry for the late, in lib/networks/VGGnet_train.py

**Comment by lxx1884896** [comment]
@eragonruan Thanks for your reply,and I have solved the problem about ten days ago.

**Comment by FantDing** [comment]
@lxx1884896 I use pretrained resnet, and find that the result is so bad. How did you solve that? Thanks

**Comment by TianboChen** [comment]
@lxx1884896 @FantDing How is the result with resnet?
