### ISSUE TITLE
inside_weights when compute reg_loss

### ISSUE THREAD

**Issue by FantDing** [eragonruan/text-detection-ctpn#145]
I read the code and noticed that `RPN_BBOX_INSIDE_WEIGHTS` is setted as `[0, 1, 0, 1]`, which means that `x_center` and `delta_width` are not regarded as the part of the `regression_loss`. I wanna to the know the reason. Thanks a lot !

**Comment by YangJiao1996** [comment]
@FantDing You can refer the 3.1 and 3.4 section of the paper. According to the paper, only the vertical coordinates are taken into consideration when building the regression loss. Horizontal coordinates are used in side-refinement part, which is NOT implemented in this repo.
