### ISSUE TITLE
total loss: nan, model loss: nan, rpn_loss_cls: nan, rpn_loss_box: nan, lr: 0.000010

### ISSUE THREAD

**Issue by small-wong** [eragonruan/text-detection-ctpn#148]
When I try to train my own model using other datasets, I always met with this problem:
**iter: 4800 / 50000, total loss: nan, model loss: nan, rpn_loss_cls: nan, rpn_loss_box: nan, lr: 0.000010**
How can I fix this?

**Comment by gt-jiayu** [comment]
I met with this problem too, have you solved this problem?

**Comment by small-wong** [comment]
@gt-jiayu I have solved the problem. You can check this [site](https://blog.csdn.net/hongxingabc/article/details/79048531), hope it may help you. Good luck~
