### ISSUE TITLE
how to run the train scripts

### ISSUE THREAD

**Issue by jibadallz** [eragonruan/text-detection-ctpn#156]
在split_label.py中有两个路径path = '/media/D/code/OCR/text-detection-ctpn/data/mlt_english+chinese/image'和gt_path = '/media/D/code/OCR/text-detection-ctpn/data/mlt_english+chinese/label'，代码中会分别读取这个两个路径下的文件，请问....../label中放什么样的文件？谢谢

**Comment by gt-jiayu** [comment]
label中的文件是txt文件，包含的是对应的图片中文本框的坐标（格式为x1, y1, x2, y2, x3, y3, x4, y4），很多公开数据集提供了这种标签

**Comment by jibadallz** [comment]
@gt-jiayu 解决了，感谢

**Comment by kajdkfksncnd** [comment]
请问楼主，我下载了您的VOCdevkit放在了data目录下，path和gt_path应该怎么修改？

**Comment by eragonruan** [comment]
@kajdkfksncnd the data I provided has been processed, you can skip prepare dataset

**Comment by gt-jiayu** [comment]
@Wangweilai1 这个你可以打开txt文件看x1, y1, x2, y2, x3, y3, x4, y4，判断一下就好。我用的之前天池大赛的标注数据，分别代表左上、左下、右下、右上

**Comment by rochesterlmg** [comment]
请问gt_path 下的*.txt文件如何产生啊，测试集里的标注是*.xml格式的，能贴下代码吗？
