### ISSUE TITLE
Could you put your dataset and model in baidu yunpan?

### ISSUE THREAD

**Issue by chinakook** [eragonruan/text-detection-ctpn#16]
R.T.
Thanks, very much!

**Comment by eragonruan** [comment]
@chinakook you can find all you need in this [link](https://pan.baidu.com/s/1kUNTl1l)

**Comment by chinakook** [comment]
@eragonruan Thanks, very much, you are really a good guy!

**Comment by hqliling** [comment]
i get your data in this link, but ,why i can't run train? open the file 'VOCdevkit', i find img 'img_1001.jpg', whose shape is 767*600, but in file 'img_1001.xml':
                <width>400</width>
		<height>313</height>
who can tell me why?Thank you!

**Comment by hqliling** [comment]
oh,i know, it's in different scales.
