### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by honghande** [eragonruan/text-detection-ctpn#161]
File "/home/hjq/PycharmProjects/Tensorflow-OCR/text-detection-ctpn-master/ctpn/demo.py", line 103, in <module>
    raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by Mary2333** [comment]
Hi, I met the same problem today, the problem is the ckpt is null, so the issue is occured.
try:
        ckpt = tf.train.get_checkpoint_state(cfg.TEST.checkpoints_path)
        print('Restoring from {}...'.format(ckpt.model_checkpoint_path), end=' ')
        saver.restore(sess, ckpt.model_checkpoint_path)
        print('done')
    except:
        raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)

I solved the issue by the following steps, and hope it's useful to you.

1. new a directory and named checkpoints under text-detection-ctpn-master.
2.download the checkpoins.zip file, and unzip it to the checkpoints directory.
3.rerun, the issue is solved.
Good luck!

**Comment by xiakun123** [comment]
Where is  the checkpoins.zip file?

**Comment by Polaris-SDU** [comment]
I also not found the ckpt file in the web.but you can train the CTPN firstly according the auther's instructions.After training,copy the ckpt file to ./text-detection-ctpn/checkpoints, then you can run the demo successfully. @ @honghande

**Comment by tjq9526** [comment]
@Mary2333  I can not find  checkpoins.zip file,can you share you checkpoins.zip file

**Comment by eragonruan** [comment]
@tjq9526 @Polaris-SDU @honghande I moved the checkpoints to [release](https://github.com/eragonruan/text-detection-ctpn/releases)

**Comment by Polaris-SDU** [comment]
Thank you @eragonruan

**Comment by Aditya-11** [comment]
Thank you @Mary2333  and @eragonruan

**Comment by javanoclaw** [comment]
http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz

**Comment by youngZhen** [comment]
Maybe the path is not right,the path of checkpoints file is  the upper folder of the demo.py file.
 I solved the issue by changing the path.

# tf.app.flags.DEFINE_string('test_data_path', 'data/demo/', '')
tf.app.flags.DEFINE_string('test_data_path', '../data/demo/', '')
# tf.app.flags.DEFINE_string('output_path', 'data/res/', '')
tf.app.flags.DEFINE_string('output_path', '../data/res/', '')
# tf.app.flags.DEFINE_string('checkpoint_path', 'checkpoints_mlt/', '')
tf.app.flags.DEFINE_string('checkpoint_path', '../checkpoints_mlt/', '')

**Comment by youngZhen** [comment]
Maybe the path is not right,the path of checkpoints file is the upper folder of the demo.py file.
I solved the issue by changing the path.

tf.app.flags.DEFINE_string('test_data_path', '**../**data/demo/', '')
tf.app.flags.DEFINE_string('output_path', '**../**data/res/', '')
tf.app.flags.DEFINE_string('checkpoint_path', '**../**checkpoints_mlt/', '')

**Comment by youngZhen** [comment]
Maybe the path is not right,the path of checkpoints file is the upper folder of the demo.py file.
I solved the issue by changing the path.


tf.app.flags.DEFINE_string('test_data_path', '../data/demo/', '')
tf.app.flags.DEFINE_string('output_path', '../data/res/', '')
tf.app.flags.DEFINE_string('checkpoint_path', '../checkpoints_mlt/', '')

**Comment by jandy0414** [comment]
> Maybe the path is not right,the path of checkpoints file is the upper folder of the demo.py file.
> I solved the issue by changing the path.
> 
> tf.app.flags.DEFINE_string('test_data_path', '../data/demo/', '')
> tf.app.flags.DEFINE_string('output_path', '../data/res/', '')
> tf.app.flags.DEFINE_string('checkpoint_path', '../checkpoints_mlt/', '')

u'r right!!  thanks!

**Comment by huahuabai** [comment]
> ../checkpoints_mlt/

Thank you! you are right!

**Comment by sickbaimu** [comment]
> tf.app.flags.DEFINE_string('test_data_path', '../data/demo/', '')
> tf.app.flags.DEFINE_string('output_path', '../data/res/', '')
> tf.app.flags.DEFINE_string('checkpoint_path', '../checkpoints_mlt/', '')

Thank you very much, you have resolved my problems.

**Comment by turbo77xx** [comment]
> Maybe the path is not right,the path of checkpoints file is the upper folder of the demo.py file. I solved the issue by changing the path.
> 
> tf.app.flags.DEFINE_string('test_data_path', '../data/demo/', '') tf.app.flags.DEFINE_string('output_path', '../data/res/', '') tf.app.flags.DEFINE_string('checkpoint_path', '../checkpoints_mlt/', '')

Thank you very much!
