### ISSUE TITLE
how to run :ln -s TEXTVOC VOCdevkit2007 on win10?

### ISSUE THREAD

**Issue by baiwuchang** [eragonruan/text-detection-ctpn#163]
i have ran :ln -s TEXTVOC VOCdevkit2007  on cygwin
![image](https://user-images.githubusercontent.com/20315459/40294629-fd434a84-5d08-11e8-8b44-fa0d0c074f9a.png)

![image](https://user-images.githubusercontent.com/20315459/40294670-25e5ee88-5d09-11e8-9830-39cf1ba5f0ba.png)

when i run : python ./ctpn/train_net.py   on cygwin,  it suggests that  the  path doesn't exist

![image](https://user-images.githubusercontent.com/20315459/40294425-1d9f8bcc-5d08-11e8-961b-e913a6608af0.png)

but when i run : cd data/TEXTVOC/VOC2007/ImageSets/Main , it suggests that  the  path  really exists

![image](https://user-images.githubusercontent.com/20315459/40294888-f500a690-5d09-11e8-99b3-2850eb66af99.png)

what should i do? i don't want to give up
thanks for help : )

**Comment by eragonruan** [comment]
@baiwuchang you can find the answer in this [page](https://stackoverflow.com/questions/3648819/how-to-make-symbolic-link-with-cygwin-in-windows-7), or just rename the folder since this step is just creating a softlink
