### ISSUE TITLE
where is the tensorflow model for demo

### ISSUE THREAD

**Issue by yuandaxing** [eragonruan/text-detection-ctpn#164]
HI, 
  I could not find any tensorflow model for demo, in readme, you have mentioned there is one.

**Comment by eragonruan** [comment]
@yuandaxing hi, I have moved the checkpoints to [release](https://github.com/eragonruan/text-detection-ctpn/releases), download the checkpoints and unzip it in data/

**Comment by yuandaxing** [comment]
thanks
