### ISSUE TITLE
prepare my own training data

### ISSUE THREAD

**Issue by yuandaxing** [eragonruan/text-detection-ctpn#169]
Hi.
   I use VOC 2007 to train and test successfully.
Now i want to prepare my own data. I notice someone have asked the question before, but i still could not understand. below is my question.
1. VOC 2007 bounding box is character based, for example, "what" have 4 bounding box, If i prepare my data, shall i have to annotate character?
2. How to prepare negative data, could you give more detail?

I think many readers need to train their own model, it is better to have more details here.

**Comment by eragonruan** [comment]
@yuandaxing label in word level or line level is ok. no need to label the character.
the negative sample will be generated during training automaticlly
