### ISSUE TITLE
how to segment the characters for recognition

### ISSUE THREAD

**Issue by SolinTao** [eragonruan/text-detection-ctpn#170]
你好，感谢分享。
请教下在找出一行文字以后，怎么能分割出单个字体，然后识别？看到很多人用的都是二值化，太容易受环境影响。

**Comment by eragonruan** [comment]
@SolinTao for now, most state-of-the-art method for recognition is end-to-end. you don't have the segment the character first. you can check CRNN for more detail.

**Comment by SolinTao** [comment]
@eragonruan Thanks for your reply. I used Faster RCNN to identify the character. However, when the font is close to each other, the edge of RCNN is not very accurate.
