### ISSUE TITLE
how to improve the accuracy of result?

### ISSUE THREAD

**Issue by jeremycurrygit** [eragonruan/text-detection-ctpn#175]
the result:
![qq 20180605155653](https://user-images.githubusercontent.com/13865358/40962871-68a30a54-68d9-11e8-866c-87d52fe16698.png)

how to get the pure text region?
is there any configuration parameters to improve the accuracy?@eragonruan

**Comment by eragonruan** [comment]
@jeremycurrygit 
- set [LINE_MIN_SCORE](https://github.com/eragonruan/text-detection-ctpn/blob/37993c4b1a8e83cb6f5013efcff546d7ec87c16c/lib/text_connector/text_connect_cfg.py#L7) to 0.95 or even higher
- finetune the model
