### ISSUE TITLE
What is the batch_size during training and how can it be modified is it the one in yml file or the one in config file of fast rcnn

### ISSUE THREAD

**Issue by chariot1498** [eragonruan/text-detection-ctpn#184]

**Comment by chariot1498** [comment]
I also tried printing it in get_minibatch function it returned 1 plus when i made the first argument of tf.placeholder as 1 which is the batch size it gave me error plus i tried integrating ctc loss in it . It gives me error regarding batch_size

**Comment by eragonruan** [comment]
@chariot1498 hi, the training batch size is 1. which means one image per batch. the parameter in [yml](https://github.com/eragonruan/text-detection-ctpn/blob/37993c4b1a8e83cb6f5013efcff546d7ec87c16c/ctpn/text.yml#L14) is the batch size of proposals
