### ISSUE TITLE
run ./make.sh error.

### ISSUE THREAD

**Issue by JanzZhu** [eragonruan/text-detection-ctpn#185]
`++ python setup.py build_ext --inplace
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
building 'utils.bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/test/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/test/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/test/anaconda3/include/python3.6m -c bbox.c -o build/temp.linux-x86_64-3.6/bbox.o -Wno-cpp -Wno-unused-function
creating /home/test/orc_gc/chinese_ocr-master/ctpn/lib/utils/utils
gcc -pthread -shared -B /home/test/anaconda3/compiler_compat -L/home/test/anaconda3/lib -Wl,-rpath=/home/test/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/bbox.o -o /home/test/orc_gc/chinese_ocr-master/ctpn/lib/utils/utils/bbox.cpython-36m-x86_64-linux-gnu.so
/home/test/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/test/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
`

Please anyone help me

**Comment by niddal-imam** [comment]
I am facing the same issue.  How did you solve it? Can you share the solution.

**Comment by 1810325** [comment]
@JanzZhu 请问你这个问题解决了吗，能蹦教一下啊，十分感谢
