### ISSUE TITLE
Is this model acyclic？Can I convert it into coreml？

### ISSUE THREAD

**Issue by BIOTONIC** [eragonruan/text-detection-ctpn#186]
I've converted the ckpt file the author gave into pb format by referring to [this solution](https://stackoverflow.com/a/45868106).
The value I set for param 'output_node_names' was 'rpn_cls_prob'.
The pb file I got seemed ok but error orcured when I tried to [convert it into coreml format](https://github.com/tf-coreml/tf-coreml).
It said "ValueError: Graph has cycles". [Issue124](https://github.com/tf-coreml/tf-coreml/issues/124) [Issue189](https://github.com/tf-coreml/tf-coreml/issues/189)
I wonder whether this model has a cycle and whether it can be converted into coreml.
Anyone have ideas?

**Comment by eragonruan** [comment]
@BIOTONIC hi, you can check this [issue](https://github.com/eragonruan/text-detection-ctpn/issues/38)

**Comment by BIOTONIC** [comment]
@eragonruan Like what you said in that issue, I want to put this model onto mobile. However, what are those output node names that I should set? 
I've tried to set output_node_names=['Reshape_5','rpn_bbox_pred/Reshape'], but found they are not in the graph.
Any ideas?

**Comment by eragonruan** [comment]
@BIOTONIC hi, I have release the pb file. close for now

**Comment by ajinkya933** [comment]
@eragonruan please attach a link for the pb file.
