### ISSUE TITLE
ascii decode error.

### ISSUE THREAD

**Issue by jesen8** [eragonruan/text-detection-ctpn#191]
![default](https://user-images.githubusercontent.com/33971685/42123938-f422e3c6-7c8c-11e8-95b5-777baf9c58d6.png)
when i download the code and try to run it ,but...can't,please help me,thanks.

**Comment by eragonruan** [comment]
@jesen8 comment out this [line](https://github.com/eragonruan/text-detection-ctpn/blob/f4b6179467cac39b70365aa926c65746aa1789cb/lib/rpn_msr/proposal_layer_tf.py#L45)

**Comment by jesen8** [comment]
ok,it's run~,thanks
