### ISSUE TITLE
load pretrained model, i.e., VGG_imagenet.npy, failed!

### ISSUE THREAD

**Issue by cltdevelop** [eragonruan/text-detection-ctpn#198]
Hello, thank you for sharing your code. It is really a good work.
when I run your code for training, I encounter a problem as follows:

in train.py, raise 'check your pretrained model {:s}'.format(self.pretrained_model), TypeError: exceptions must be old-style classes or derived from BaseException, not str.

So I debug this error, and I found that when when I run this code, i.e., data_dict = np.load(data_path, encoding='latin1').item(), which is the loading pretrained model VGG_imagenet.npy. Lastly, I just load this npy file, it also report an error as follows:

'Failed to interpret file %s as a pickle'. 

I run this code in python2.7. 
Can you give me some advice? Thank you!

**Comment by cltdevelop** [comment]
I have handled this bug. I found that this original file, i.e., VGG_imagenet.npy, is not valid. So I download a new VGG_imagenet.npy from this link: https://drive.google.com/file/d/0B4WygwSE8o2PUFZYSEJBOW9hZnM/view

**Comment by scaler2017** [comment]
pip install numpy==1.16.2  is good for me.
