### ISSUE TITLE
How to resume training (finetuning) on the checkpoint(saved) model?

### ISSUE THREAD

**Issue by vodanhqt92** [eragonruan/text-detection-ctpn#206]
For example, I have trained a model for 50,000 rounds, and save the model successfully. What if I want to go on training base on the saved model, saying, I want to train 50,000 more rounds. I can not find some documentation. Does anybody know the command details? @eragonruan

**Comment by vodanhqt92** [comment]
I solved it.

**Comment by chinesesuperliu** [comment]
hi @vodanhqt92,  I have same question about what you mentioned above. Would you please tell me how do you solve it?  Thanks a lot
