### ISSUE TITLE
Windows 10 Build Issue 

### ISSUE THREAD

**Issue by ankur7721** [eragonruan/text-detection-ctpn#207]
Environment details
```
OS: Win 10 - GPU(MX150)
CUDA: 9.2
CuDnn: 7.1.4
Python:3.6 (Anaconda)
OpenCV: 3.3.1
Cython: 0.28.3
Tensorflow: 1.9
```

Cuda installation is successful as nvcc --version returns 

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:08:12_Central_Daylight_Time_2018
Cuda compilation tools, release 9.2, V9.2.148
```
Now I am trying to build the repo.
commands mentioned in make.sh are 
```

cython bbox.pyx
cython cython_nms.pyx
cython gpu_nms.pyx
python setup.py build_ext --inplace
rm -rf build
```

I am able to successfully run first three commands, but when i try to run `python setup.py build_ext --inplace` I see the following error

```
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 39, in locate_cuda
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v_new))
OSError: The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\nvcc
```

I tried all combinations of escaping backslash but it doesn't work. Moreover the nvcc executable exists here `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\nvcc`

Could it be a permission issue ? or something else?

**Comment by yulinxuanzhi** [comment]
Hello @ankur7721 ，have you built the lib successful with GPU on Windows 10 platform?
