### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xiaomaxiao** [eragonruan/text-detection-ctpn#23]
run demo.py

InvalidArgumentError (see above for traceback): TypeError: 'NoneType' object is not subscriptable

[[Node: rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5/_75, rpn_bbox_pred/Reshape/_77, _arg_Placeholder_1_0_1, rois/PyFunc/input_3, rois/PyFunc/input_4, rois/PyFunc/input_5)]]

[[Node: rois/PyFunc/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_290_rois/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

`

**Comment by eragonruan** [comment]
Can you provide more detail about the error? Are you using cpu device?

**Comment by xiaomaxiao** [comment]
@eragonruan 
WIN10 ,TF 1.3.    
Do not support windows?



during handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-0f63f2fd967f> in <module>()
    103     im = 128 * np.ones((300, 300, 3), dtype=np.uint8)
    104     for i in range(2):
--> 105         _, _ = test_ctpn(sess, net, im)
    106 
    107     im_names = glob.glob(os.path.join(cfg.DATA_DIR, 'demo', '*.png')) +                glob.glob(os.path.join(cfg.DATA_DIR, 'demo', '*.jpg'))

E:\deeplearn\OCRonline\text-detection-ctpn\lib\fast_rcnn\test.py in test_ctpn(sess, net, im, boxes)
     49         feed_dict = {net.data: blobs['data'], net.im_info: blobs['im_info'], net.keep_prob: 1.0}
     50 
---> 51     rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
     52     rois=rois[0]
     53 

C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

**Comment by xiaomaxiao** [comment]
@eragonruan 

`
def test_ctpn(sess, net, im, boxes=None):
    blobs, im_scales = _get_blobs(im, boxes)
    if cfg.TEST.HAS_RPN:
        im_blob = blobs['data']
        blobs['im_info'] = np.array(
            [[im_blob.shape[1], im_blob.shape[2], im_scales[0]]],
            dtype=np.float32)
    # forward pass
    if cfg.TEST.HAS_RPN:
        feed_dict = {net.data: blobs['data'], net.im_info: blobs['im_info'], net.keep_prob: 1.0}

   #！！！！ rois->rpn_cls_prob_reshape
    rois = sess.run([net.get_output('rpn_cls_prob_reshape')[0]],feed_dict=feed_dict)
  

    `


der_1:0", shape=(?, 3), dtype=float32)
Loading network VGGnet_test...  Restoring from E:\deeplearn\OCRonline\text-detection-ctpn\checkpoints\VGGnet_fast_rcnn_iter_50000.ckpt... INFO:tensorflow:Restoring parameters from E:\deeplearn\OCRonline\text-detection-ctpn\checkpoints\VGGnet_fast_rcnn_iter_50000.ckpt
done
 done.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for E:\deeplearn\OCRonline\text-detection-ctpn\data\demo\010.png
Detection took 0.059s for 37 object proposals
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-a29ad8c3e414> in <module>()
    112         print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    113         print(('Demo for {:s}'.format(im_name)))
--> 114         ctpn(sess, net, im_name)

<ipython-input-1-a29ad8c3e414> in ctpn(sess, net, image_name)
     70     keep = np.where(dets[:, 4] >= 0.7)[0]
     71     dets = dets[keep, :]
---> 72     line = connect_proposal(dets[:, 0:4], dets[:, 4], im.shape)
     73     save_results(image_name, im, line,thresh=0.9)
     74

**Comment by xiaomaxiao** [comment]
I found that the error was caused by the NMS. 

I will continue debugging

**Comment by frankzhuo** [comment]
can you describe more it detaily ???,i ,met this problem , tear
