### ISSUE TITLE
WHERE ARE gt_img_1001.txt ... gt_img_6000.txt FILES?!

### ISSUE THREAD

**Issue by maky-hnou** [eragonruan/text-detection-ctpn#235]
I cloned the project, downloaded the pretrained model and the training data, unzipped them then got a folder named `TEXTVOC` that contains other folders (Annotations, ImagesSets and JPEGImages). I placed TEXTVOC in the `data` folder and edited the paths in the split_label.py as following: 
`path = '/home/hani/Desktop/text-detection-ctpn/data/TEXTVOC/JPEGImages'`
`gt_path = '/home/hani/Desktop/text-detection-ctpn/data/TEXTVOC/Annotations'`. 
But, when I run it `python lib/prepare_training_data/split_label.py`, I got this error:

```
/home/hani/Desktop/text-detection-ctpn/data/TEXTVOC/JPEGImages/img_1001.jpg
Traceback (most recent call last):
  File "lib/prepare_training_data/split_label.py", line 34, in <module>
    with open(gt_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hani/Desktop/text-detection-ctpn/data/TEXTVOC/Annotations/gt_img_1001.txt'
```
As it is shown, the `gt_img_1001.txt` is not missing, which means whether the **gt_path** is wrong whether those files do not exist. I looked into all folders and I didn't find any file starting with `gt_`*
**PS:** I also run this command: `ln -s TEXTVOC VOCdevkit2007`, so I didn't miss anything that should be done.

**Comment by yharshavardhan97** [comment]
I think each .txt should contain the bounding box coordinates of the respective image

**Comment by maky-hnou** [comment]
Thank you

**Comment by yharshavardhan97** [comment]
@maky-hnou , do you know how to fine tune this model with our own dataset??
