### ISSUE TITLE
After CTPN. What is your idea?

### ISSUE THREAD

**Issue by JeonghanSeock** [eragonruan/text-detection-ctpn#24]
Hello. eragonruan!
I was very impressed with your code.
One more time. Thank you so much.

I have a problem.
When the image passes through the CTPN, a green box is created.
If I put this image in the OCR engine, how should I separate it (green box)?
My idea is to use OpenCV.
But the green box is on the text. so it hides the text.
Can I draw a thin line to solve the problem?

**Comment by eragonruan** [comment]
@JeonghanSeock 
`def cut(image_name, im, line, thresh=0.9):
    inds = np.where(line[:, -1] >= thresh)[0]
    for i in inds:
        bbox = line[i, :4]
        img = im[int(bbox[1]):int(bbox[3]), int(bbox[0]):int(bbox[2]), :]
        folder = 'seg_all/' + image_name.split('/')[-1].split('.')[0]
        if not os.path.exists(folder):
            os.makedirs(folder)
        filename = os.path.join(folder, '{:03d}'.format(i) + '.jpg')
        cv2.imwrite(filename, img)


def ctpn(sess, net, image_name):
    img = cv2.imread(image_name)
    im = check_img(img)

    scores, boxes = test_ctpn(sess, net, im)
    NMS_THRESH = 0.3
    dets = np.hstack((boxes, scores[:, np.newaxis])).astype(np.float32)
    keep = nms(dets, NMS_THRESH)
    dets = dets[keep, :]

    keep = np.where(dets[:, 4] >= 0.7)[0]
    dets = dets[keep, :]
    line = connect_proposal(dets[:, 0:4], dets[:, 4], im.shape)
    cut(image_name, im, line, thresh=0.9)`
you can use this code I write before, it will save all detection result to disk

**Comment by JeonghanSeock** [comment]
Wow.. thank you very much! kind of you~!

**Comment by Kumara-Kaushik** [comment]
Hi, Can you please explain what the input to "line" is in the above function? I having trouble integrating the function in the code

**Comment by eragonruan** [comment]
@Kumara-Kaushik it looks like this [xmin,ymin,xmax,ymax,score]

**Comment by Kumara-Kaushik** [comment]
thanks @eragonruan I got it working.

**Comment by qdzhangyuhui** [comment]
> thanks @eragonruan I got it working.

hi how to use this cut function？

**Comment by qdzhangyuhui** [comment]
> thanks @eragonruan I got it working.

@Jeonghan-Seok @eragonruan @Jeonghan-Seok

**Comment by 1810325** [comment]
@Jeonghan-Seok 你好， 我看了好久都没有编译出.so文件，希望得到你的帮助，如果可以能加我微信吗love_qinging

**Comment by akshadaas** [comment]
> @JeonghanSeock
> `def cut(image_name, im, line, thresh=0.9): inds = np.where(line[:, -1] >= thresh)[0] for i in inds: bbox = line[i, :4] img = im[int(bbox[1]):int(bbox[3]), int(bbox[0]):int(bbox[2]), :] folder = 'seg_all/' + image_name.split('/')[-1].split('.')[0] if not os.path.exists(folder): os.makedirs(folder) filename = os.path.join(folder, '{:03d}'.format(i) + '.jpg') cv2.imwrite(filename, img)`
> you can use this function in demo/ctpn function , it will save all detection result to disk

I dont understand where to put this code. And from where to call it?

**Comment by eyagarci** [comment]
Hi @Jeonghan-Seok !
I need your help. Can you explain to me how to read ctpn model using opencv

I use the ctpn.pb file of @eragonruan project and I generate the .pbtxt graph.

cvNet = cv.dnn.readNetFromTensorflow('ctpn.pb', 'protobuf.pbtxt')
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_io.cpp:54: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: protobuf.pbtxt in function 'cv::dnn::ReadTFNetParamsFromTextFileOrDie'
