### ISSUE TITLE
There are confusing parts.

### ISSUE THREAD

**Issue by JeonghanSeock** [eragonruan/text-detection-ctpn#25]
Hello.
eragonruan!
I have some question.

I tried running the "./ctpn/train_net.py" file in Google Cloud Compute.
I have modified max_iters = 60000 to max_iters = 500 and ran it. (for test)
The output folder is created and a new checkpoint is created.
The new checkpoint folder has been move to "text-detection-ctpn/checkpoint". Then I ran "demo.py" and it did not have any errors.
But, There is nothing in the results folder.

(1) Is it because I set the training smaller? (max_iters = 500)
(2) new training -> The new checkpoint is created. but what is "VGG_imagenet.npy" file?
You have provided two pre-trained images.
one, checkpoints. ex) VGGnet_fast_rcnn_iter_50000.ckpt.data-00000-of-00001
two, data/pretrain. ex) VGG_imagenet.npy
checkpoints/train-informations vs data/pretrain/VGG_imagenet.npy
What is the difference between the two?
and Why I need VGG_imagenet.npy and How make own VGG_imagenet.npy.

I would be grateful if you could answer the question.
Thank you sooo much.

**Comment by JeonghanSeock** [comment]
I have trained max_iters = 60000, and run demo.
But, Nothing in a result folder...

**Comment by cjt222** [comment]
VGG_imagenet.npy is pretrained model in imagenet, VGGnet_fast_rcnn_iter_50000.ckpt.data-00000-of-00001 is a model which has been trained well

**Comment by eragonruan** [comment]
@JeonghanSeock yes, since the model did not converge， it can detect nothing, so no result will be saved.
Second, VGG is used to initialize model's weight to accelerate the convergence

**Comment by JeonghanSeock** [comment]
Thank you soooo much guys!!
