### ISSUE TITLE
四边形的训练数据集

### ISSUE THREAD

**Issue by lxx1884896** [eragonruan/text-detection-ctpn#259]
谢谢你分享的代码，但我注意到ctpn中训练应该用到的是矩形框的训练集，而MLT中的训练集标签为四边形的，我在split_label.py中看到你做了处理来适应训练，我想这是不是会影响最终的测试f-score,因为ctpn论文中显示f-score为0.88，我用你提供的方法训练后f-score 大概为0.79左右。

**Comment by lxx1884896** [comment]
@zwl22 ,你好，是用icdar2013的测试集测的。

**Comment by eragonruan** [comment]
@lxx1884896 你好，最新的代码重新处理了四边形标注的训练集，相对比之前的处理精细一些。
