### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by SuryaprakashNSM** [eragonruan/text-detection-ctpn#26]
When I try to execute the demo.py im receiving this error 

 File "demo.py", line 9, in <module>
    from lib.networks.factory import get_network
ModuleNotFoundError: No module named 'lib'

Can someone please help me with this ?

**Comment by eragonruan** [comment]
@SuryaprakashNSM did you run demo in the root directory?

**Comment by SuryaprakashNSM** [comment]
No, from ..\text-detection-ctpn\ctpn directory.

**Comment by eragonruan** [comment]
you should run in text-detection-ctpn directory

**Comment by SuryaprakashNSM** [comment]
Yeah .. that helped. Also Im trying to run it windows. 
Is there an alternate for these:

cd lib/utils
chmod +x make.sh
./make.sh

**Comment by eragonruan** [comment]
@SuryaprakashNSM yes, just open make.sh and execute the code one by one

**Comment by cjt222** [comment]
hello，when i run it on windows，it may cause some errors。when i run python setup.py build_ext --inplace， some errors like below，windows may do not has so file, do you have solution? thanks so   @much!!!
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so' @eragonruan @SuryaprakashNSM

**Comment by eragonruan** [comment]
I did not test on windows, building python library in windows is inconvenient, you can use nms implemented in pure python instead

**Comment by SuryaprakashNSM** [comment]
@cjt222  Yeah right now I am facing the same issue. @eragonruan can u help us with this error.

![image](https://user-images.githubusercontent.com/24566661/32713840-07dbc6ba-c871-11e7-911b-c5494de0550e.png)

**Comment by eragonruan** [comment]
I will test on windows soon.

**Comment by SuryaprakashNSM** [comment]
Thanks man .. U r the best.

**Comment by eragonruan** [comment]
@SuryaprakashNSM you can delete code reelated to cuda in setup.py and use bbox and nms implemented in cython. you can use mingw32 or vs to build these two modules. but this process may be trouble some, you can refer to this [page](https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_Cython_On_Anaconda_On_Windows?lang=zh).
Or you can use nms and bbox implemented in pure python which do not need to build.
py_nms
`import numpy as np

def nms(dets, thresh):
    x1 = dets[:, 0]
    y1 = dets[:, 1]
    x2 = dets[:, 2]
    y2 = dets[:, 3]
    scores = dets[:, 4]

    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])

        w = np.maximum(0.0, xx2 - xx1 + 1)
        h = np.maximum(0.0, yy2 - yy1 + 1)
        inter = w * h
        ovr = inter / (areas[i] + areas[order[1:]] - inter)

        inds = np.where(ovr <= thresh)[0]
        order = order[inds + 1]

    return keep
`

py_bbox
`import numpy as np

def bbox_overlaps(boxes,query_boxes):

    N = boxes.shape[0]
    K = query_boxes.shape[0]
    overlaps = np.zeros((N, K))
    for k in range(K):
        box_area = (
            (query_boxes[k, 2] - query_boxes[k, 0] + 1) *
            (query_boxes[k, 3] - query_boxes[k, 1] + 1)
        )
        for n in range(N):
            iw = (
                min(boxes[n, 2], query_boxes[k, 2]) -
                max(boxes[n, 0], query_boxes[k, 0]) + 1
            )
            if iw > 0:
                ih = (
                    min(boxes[n, 3], query_boxes[k, 3]) -
                    max(boxes[n, 1], query_boxes[k, 1]) + 1
                )
                if ih > 0:
                    ua = float(
                        (boxes[n, 2] - boxes[n, 0] + 1) *
                        (boxes[n, 3] - boxes[n, 1] + 1) +
                        box_area - iw * ih
                    )
                    overlaps[n, k] = iw * ih / ua
    return overlaps

def bbox_intersections(boxes,query_boxes):

    N = boxes.shape[0]
    K = query_boxes.shape[0]
    intersec = np.zeros((N, K))

    for k in range(K):
        box_area = (
            (query_boxes[k, 2] - query_boxes[k, 0] + 1) *
            (query_boxes[k, 3] - query_boxes[k, 1] + 1)
        )
        for n in range(N):
            iw = (
                min(boxes[n, 2], query_boxes[k, 2]) -
                max(boxes[n, 0], query_boxes[k, 0]) + 1
            )
            if iw > 0:
                ih = (
                    min(boxes[n, 3], query_boxes[k, 3]) -
                    max(boxes[n, 1], query_boxes[k, 1]) + 1
                )
                if ih > 0:
                    intersec[n, k] = iw * ih / box_area
    return intersec`

**Comment by ankur7721** [comment]
@eragonruan @SuryaprakashNSM I am facing similar issue, Can either of you tell me how would modified setup.py would look like ? post the same instead of only smaller snippet, since I am not able to find which parts to delete.
