### ISSUE TITLE
VGGnet_train.py中部分参数不知道是怎么来的

### ISSUE THREAD

**Issue by youhuabin** [eragonruan/text-detection-ctpn#261]
你好，谢问
(self.feed('lstm_o').lstm_fc(512,len(anchor_scales) * 10 * 4, name='rpn_bbox_pred'))
(self.feed('lstm_o').lstm_fc(512,len(anchor_scales) * 10 * 2,name='rpn_cls_score'))
中的len(anchor_scales) * 10 * 4 和 len(anchor_scales) * 10 * 2 是根据什么得来的

**Comment by eragonruan** [comment]
@youhuabin 你好，一共有10种不同高度的anchor。bbox_pred预测四个相对anchor的偏移距离，cls_score预测每个anchor文本/非文本的分数。
