### ISSUE TITLE
作者提供的训练集，image和label不是对应的？把gt画在原图上，都是错乱的==

### ISSUE THREAD

**Issue by Lumaess** [eragonruan/text-detection-ctpn#266]
像这张：
<img width="631" alt="2019-01-04 7 14 18" src="https://user-images.githubusercontent.com/34794491/50685668-0f82b680-1055-11e9-8ec1-ed5ba3916df8.png">

**Comment by Lumaess** [comment]
打开几张图片，对比了下width和height，发现xml文件里的信息和image的信息也不对应。。这份数据有毛病吗请问？
<img width="663" alt="2019-01-04 7 16 31" src="https://user-images.githubusercontent.com/34794491/50685914-3b526c00-1056-11e9-9356-2093c3f99867.png">

**Comment by sibosutd** [comment]
1. image 和 label 对应，需要按照图片的 width 和 height 来画
![img_1002](https://user-images.githubusercontent.com/10401996/50891623-ab3a6b00-1437-11e9-8bf6-7ab4b91fa181.png)

2. xml 里面是原始宽高，image 的宽高是被 resize 过的

**Comment by Lumaess** [comment]
> 1. image 和 label 对应，需要按照图片的 width 和 height 来画
>    ![img_1002](https://user-images.githubusercontent.com/10401996/50891623-ab3a6b00-1437-11e9-8bf6-7ab4b91fa181.png)
> 2. xml 里面是原始宽高，image 的宽高是被 resize 过的

感谢🙏！
