### ISSUE TITLE
Now It is work! But I have a question about VGG16Net.

### ISSUE THREAD

**Issue by JeonghanSeock** [eragonruan/text-detection-ctpn#30]
After failing to train for the first time, I did not sleep for two days and did my research.
I found the optimal value by modifying the parameter part of the text.yml file. (for my computer)
I was able to solve it with your help. Thank you so much. 

I am currently researching on detecting the text in business card.
The business card image contains text, face, and company logo.
It is very different from nature image. The elements are very limited.

Anyway, (Q.1)what data did you use to train VGG16NET in advance?
(Q.2)Would it be okay if both VGG16net and fast_rcnn(CTPN) were trained in business card image?
What are your thoughts?

example)
100 million text, human face, QR code, company logo images-> training -> VGnet.
100 million business card images -> training -> CTPN.

(Q.3) If I train VGG16NET, which soure code should I use?

Thank you for your continued help.
You will receive many blessings.

**Comment by JeonghanSeock** [comment]
In this repo (https://github.com/tianzhi0549/CTPN)
Only one model is used. named "ctpn_trained_model.caffemodel"
Your code uses two models. What is the difference?
VGG_imagenet.npy and VGGnet_fast_rcnn_iter_50000.ckpt.data-00000-of-00001

**Comment by JeonghanSeock** [comment]
I am worried about which of two models to train.
because, your source code using two models (VGG_imagenet.npy and VGGnet_fast_rcnn_iter_50000.ckpt.data-00000-of-00001)
So I asked a question.
I do not know about artificial intelligence. I am just having fun. Sorry to have a basic question.

**Comment by eragonruan** [comment]
@JeonghanSeock  VGG_imagenet.npy  is pretrained in ImageNet, we do not have to train it ourselves, you can download it everywhere. VGG_imagenet.npy  is used to initialize the model in training for faster convergence. It is not a necessary, you can initialize the model with random parameter if you want, but this will take more time to converge. So you just need to train the ctpn model, for business card, you can first  train ctpn in public scene text dataset like mlt,icdar. Then finetune it by some business card images for better performance.

**Comment by JeonghanSeock** [comment]
Thank you for your advice.
You are a genius!
