### ISSUE TITLE
Would you kindly tell that only horizontal lines can be detected?

### ISSUE THREAD

**Issue by lipond** [eragonruan/text-detection-ctpn#31]
Why it doesnot work for vertical lines?

**Comment by eragonruan** [comment]
@lipond CTPN can only detect horizontal text, I have mentioned this in readme. As far as I know, most algorithms now are not able to handle vertical lines well.

**Comment by jycloud** [comment]
@eragonruan no,CTPN’s resualts are many small rectangles,which can be fitting as a big rectangle with an angle uauslly less than 45.
