### ISSUE TITLE
can't run demo.py.

### ISSUE THREAD

**Issue by hungpvchainos** [eragonruan/text-detection-ctpn#313]
error information:
from utils.bbox.bbox import bbox_overlaps
ImportError: No module named bbox.bbox
please help me !!!

**Comment by Curry30h** [comment]
how to solve this problem?

**Comment by mukeshchugani10** [comment]
How do you solve this issue?

**Comment by amughrabi** [comment]
Try to add __init__.py (empty file) into:
* nets/ 
* utils/bbox/ 
* utils/
