### ISSUE TITLE
demo.pyt runing.  cannot import name 'model_train'

### ISSUE THREAD

**Issue by baronpalacios** [eragonruan/text-detection-ctpn#316]
hello I hope you are well,
I would like you to help me with this problem.
I followed the steps they say in document README.md

1. I got the repository
2. build the library first by executing this code

`` shell
cd utils / bbox
chmod + x make.sh
./make.sh

`/home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
In file included from /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms.c:283:
/home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^~~~~~~~~~~~~
gcc -pthread -shared -B /home/harlinton/anaconda3/envs/barontext/compiler_compat -L/home/harlinton/anaconda3/envs/barontext/lib -Wl,-rpath=/home/harlinton/anaconda3/envs/barontext/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/nms.o -o build/lib.linux-x86_64-3.6/nms.cpython-36m-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.6/nms.cpython-36m-x86_64-linux-gnu.so -> /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages
running install_egg_info
Removing /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg-info
Writing /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg-info
`

3. then I downloaded the ckpt file and puted checkpoints_mlt / in text-detection-ctpn /
finally ran the demo.py

(barontext) harlinton@harlinton-UX430UNR:~/text-detection-ctpn-banjin-dev/main$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from nets import model_train as model
ImportError: cannot import name 'model_train'

I want to know if I have missed some step, because I still have this error.

My computer has Ubuntu 18.04, Tensorflow 1.8, Cuda 9.0 , python 3.6, GPU 2gm.

**Comment by baronpalacios** [comment]
> hello I hope you are well,
> I would like you to help me with this problem.
> I followed the steps they say in document README.md
> 
>     1. I got the repository
> 
>     2. build the library first by executing this code
> 
> 
> `` shell
> cd utils / bbox
> chmod + x make.sh
> ./make.sh
> 
> `/home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp] #warning "Using deprecated NumPy API, disable it by " \ ^~~~~~~ In file included from /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0, from /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4, from nms.c:283: /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: ‘_import_array’ defined but not used [-Wunused-function] _import_array(void) ^~~~~~~~~~~~~ gcc -pthread -shared -B /home/harlinton/anaconda3/envs/barontext/compiler_compat -L/home/harlinton/anaconda3/envs/barontext/lib -Wl,-rpath=/home/harlinton/anaconda3/envs/barontext/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/nms.o -o build/lib.linux-x86_64-3.6/nms.cpython-36m-x86_64-linux-gnu.so running install_lib copying build/lib.linux-x86_64-3.6/nms.cpython-36m-x86_64-linux-gnu.so -> /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages running install_egg_info Removing /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg-info Writing /home/harlinton/anaconda3/envs/barontext/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg-info `
> 
>     1. then I downloaded the ckpt file and puted checkpoints_mlt / in text-detection-ctpn /
>        finally ran the demo.py
> 
> 
> (barontext) harlinton@harlinton-UX430UNR:~/text-detection-ctpn-banjin-dev/main$ python demo.py
> Traceback (most recent call last):
> File "demo.py", line 12, in
> from nets import model_train as model
> ImportError: cannot import name 'model_train'
> 
> I want to know if I have missed some step, because I still have this error.
> 
> My computer has Ubuntu 18.04, Tensorflow 1.8, Cuda 9.0 , python 3.6, GPU 2gm.

**Comment by AhmedEssamIsmail** [comment]
@baronpalacios i have the same problem.
how did you solve it ?
