### ISSUE TITLE
 No module named 'utils.rpn_msr'

### ISSUE THREAD

**Issue by JianqingWeng** [eragonruan/text-detection-ctpn#327]

**Comment by Abdulazizbek** [comment]
I have faced also the same issue. What's wrong

**Comment by eravallirao** [comment]
ModuleNotFoundError: No module named 'utils.rpn_msr'

I am getting this error, I followed the process which is asked there. Can someone help with this

**Comment by eravallirao** [comment]
I just changed the **"utils"** to **"Utils"** whereever utils is present in the code, it worked.

**Comment by Mrlei-go** [comment]
> I just changed the **"utils"** to **"Utils"** whereever utils is present in the code, it worked.

How did you do that?Can you speak details?
