### ISSUE TITLE
TypeError: Expect argument to be a string or int

### ISSUE THREAD

**Issue by JianqingWeng** [eragonruan/text-detection-ctpn#329]

**Comment by Wo-Ki** [comment]
I have the same question when training, how to solve it?

**Comment by sxp0100** [comment]
if your error is like"IllegalFlagValueError: flag --decay_rate=0.1: Expect argument to be a string or int, found <class 'float'>",try change "tf.app.flags.DEFINE_integer('decay_rate', 0.1, '')"into"tf.app.flags.DEFINE_float('decay_rate', 0.1, '')" in train.py
