### ISSUE TITLE
Isn't there a test.py to evaluate the model after training?

### ISSUE THREAD

**Issue by xuewenyuan** [eragonruan/text-detection-ctpn#35]
After training, there is only a .ckpt file generated but not any evaluation.

**Comment by eragonruan** [comment]
@xuewenyuan yes, but I haven't release the code for now.  you can modify [ctpn/demo.py](https://github.com/eragonruan/text-detection-ctpn/blob/master/ctpn/demo.py) and save the detetction results in txt rather than drawing on images.
