### ISSUE TITLE
How can model run using multi gpus

### ISSUE THREAD

**Issue by hsddlz** [eragonruan/text-detection-ctpn#37]
Now，I can just run the model using only one gpu . Can I use multi gpus to run that, and what I need to do?

**Comment by eragonruan** [comment]
@hsddlz in order to train on multi gpus, you have to build the model on each gpu, then collect the gradients , then average it. you can find more in this [repo](https://github.com/eragonruan/refinenet-image-segmentation/blob/master/RefineNet/multi_gpu_train.py)

**Comment by burness** [comment]
Maybe  we can try the data parallelism？@eragonruan
