### ISSUE TITLE
How to freeze the model graph from ckpt?

### ISSUE THREAD

**Issue by wanghuok** [eragonruan/text-detection-ctpn#38]
I want to freeze the parameter of the model which you pretrained to one pb file.
I add some code to demo.py, but i am failed.
This work need to know the out_put_node of the model. I print out all nodes in pretrained model. and i think these two nodes maby output nodes:rois/Reshape/shape,rois/Reshape, is that right?
Here is my code:

if __name__ == '__main__':
    if os.path.exists("data/results/"):
        shutil.rmtree("data/results/")
    os.makedirs("data/results/")

    cfg_from_file('ctpn/text.yml')

    # init session
    config = tf.ConfigProto(allow_soft_placement=True)
    sess = tf.Session(config=config)
    # load network
    net = get_network("VGGnet_test")
    # load model
    print(('Loading network {:s}... '.format("VGGnet_test")), end=' ')
    saver = tf.train.Saver()

    try:
        ckpt = tf.train.get_checkpoint_state(cfg.TEST.checkpoints_path)
        #ckpt=tf.train.get_checkpoint_state("output/ctpn_end2end/voc_2007_trainval/")
        print('Restoring from {}...'.format(ckpt.model_checkpoint_path), end=' ')
        saver.restore(sess, ckpt.model_checkpoint_path)
        print('done')
    except:
        raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
    print (' done.')

    print('all nodes are:\n')
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    node_names = [node.name for node in input_graph_def.node]
    for x in node_names:
       print(x)
    output_node_names = 'rois/Reshape/shape,rois/Reshape'
    output_graph_def = graph_util.convert_variables_to_constants(sess, input_graph_def, output_node_names.split(','))
    output_graph = 'ctpn.pb'
    with tf.gfile.GFile(output_graph, 'wb') as f:
        f.write(output_graph_def.SerializeToString())
    sess.close()

**Comment by eragonruan** [comment]
@wanghuok are you trying to port the model to mobile? In test, the model output node is rois, you can find in [here](https://github.com/eragonruan/text-detection-ctpn/blob/1bb8e762bff67bf89fd635507ed105321b92f9a3/lib/fast_rcnn/test.py#L51), to be more specific, rois[0]， i.e. rpn_rois  is the output you need, see this [link](https://github.com/eragonruan/text-detection-ctpn/blob/1bb8e762bff67bf89fd635507ed105321b92f9a3/lib/networks/network.py#L180).

**Comment by wanghuok** [comment]
@eragonruan I do not want to use the model on mobile, but want to load model convenience and less memory consume. 
I have saw that code. but there is no node named 'rois' in the graph.
I output all nodes in the graph. but only find 6 nodes related to 'rois'. 
All nodes in graph are:
Placeholder
Placeholder_1
Placeholder_2
conv1_1/weights/Initializer/truncated_normal/shape
conv1_1/weights/Initializer/truncated_normal/mean
conv1_1/weights/Initializer/truncated_normal/stddev
conv1_1/weights/Initializer/truncated_normal/TruncatedNormal
conv1_1/weights/Initializer/truncated_normal/mul
conv1_1/weights/Initializer/truncated_normal
conv1_1/weights
conv1_1/weights/Assign
conv1_1/weights/read
conv1_1/weights/Regularizer/l2_regularizer/weight_decay
conv1_1/weights/Regularizer/l2_regularizer/L2Loss
conv1_1/weights/Regularizer/l2_regularizer/value
conv1_1/biases/Initializer/Const
conv1_1/biases
conv1_1/biases/Assign
conv1_1/biases/read
conv1_1/Conv2D
conv1_1/BiasAdd
conv1_1/conv1_1
conv1_2/weights/Initializer/truncated_normal/shape
conv1_2/weights/Initializer/truncated_normal/mean
conv1_2/weights/Initializer/truncated_normal/stddev
conv1_2/weights/Initializer/truncated_normal/TruncatedNormal
conv1_2/weights/Initializer/truncated_normal/mul
conv1_2/weights/Initializer/truncated_normal
conv1_2/weights
conv1_2/weights/Assign
conv1_2/weights/read
conv1_2/weights/Regularizer/l2_regularizer/weight_decay
conv1_2/weights/Regularizer/l2_regularizer/L2Loss
conv1_2/weights/Regularizer/l2_regularizer/value
conv1_2/biases/Initializer/Const
conv1_2/biases
conv1_2/biases/Assign
conv1_2/biases/read
conv1_2/Conv2D
conv1_2/BiasAdd
conv1_2/conv1_2
pool1
conv2_1/weights/Initializer/truncated_normal/shape
conv2_1/weights/Initializer/truncated_normal/mean
conv2_1/weights/Initializer/truncated_normal/stddev
conv2_1/weights/Initializer/truncated_normal/TruncatedNormal
conv2_1/weights/Initializer/truncated_normal/mul
conv2_1/weights/Initializer/truncated_normal
conv2_1/weights
conv2_1/weights/Assign
conv2_1/weights/read
conv2_1/weights/Regularizer/l2_regularizer/weight_decay
conv2_1/weights/Regularizer/l2_regularizer/L2Loss
conv2_1/weights/Regularizer/l2_regularizer/value
conv2_1/biases/Initializer/Const
conv2_1/biases
conv2_1/biases/Assign
conv2_1/biases/read
conv2_1/Conv2D
conv2_1/BiasAdd
conv2_1/conv2_1
conv2_2/weights/Initializer/truncated_normal/shape
conv2_2/weights/Initializer/truncated_normal/mean
conv2_2/weights/Initializer/truncated_normal/stddev
conv2_2/weights/Initializer/truncated_normal/TruncatedNormal
conv2_2/weights/Initializer/truncated_normal/mul
conv2_2/weights/Initializer/truncated_normal
conv2_2/weights
conv2_2/weights/Assign
conv2_2/weights/read
conv2_2/weights/Regularizer/l2_regularizer/weight_decay
conv2_2/weights/Regularizer/l2_regularizer/L2Loss
conv2_2/weights/Regularizer/l2_regularizer/value
conv2_2/biases/Initializer/Const
conv2_2/biases
conv2_2/biases/Assign
conv2_2/biases/read
conv2_2/Conv2D
conv2_2/BiasAdd
conv2_2/conv2_2
pool2
conv3_1/weights/Initializer/truncated_normal/shape
conv3_1/weights/Initializer/truncated_normal/mean
conv3_1/weights/Initializer/truncated_normal/stddev
conv3_1/weights/Initializer/truncated_normal/TruncatedNormal
conv3_1/weights/Initializer/truncated_normal/mul
conv3_1/weights/Initializer/truncated_normal
conv3_1/weights
conv3_1/weights/Assign
conv3_1/weights/read
conv3_1/weights/Regularizer/l2_regularizer/weight_decay
conv3_1/weights/Regularizer/l2_regularizer/L2Loss
conv3_1/weights/Regularizer/l2_regularizer/value
conv3_1/biases/Initializer/Const
conv3_1/biases
conv3_1/biases/Assign
conv3_1/biases/read
conv3_1/Conv2D
conv3_1/BiasAdd
conv3_1/conv3_1
conv3_2/weights/Initializer/truncated_normal/shape
conv3_2/weights/Initializer/truncated_normal/mean
conv3_2/weights/Initializer/truncated_normal/stddev
conv3_2/weights/Initializer/truncated_normal/TruncatedNormal
conv3_2/weights/Initializer/truncated_normal/mul
conv3_2/weights/Initializer/truncated_normal
conv3_2/weights
conv3_2/weights/Assign
conv3_2/weights/read
conv3_2/weights/Regularizer/l2_regularizer/weight_decay
conv3_2/weights/Regularizer/l2_regularizer/L2Loss
conv3_2/weights/Regularizer/l2_regularizer/value
conv3_2/biases/Initializer/Const
conv3_2/biases
conv3_2/biases/Assign
conv3_2/biases/read
conv3_2/Conv2D
conv3_2/BiasAdd
conv3_2/conv3_2
conv3_3/weights/Initializer/truncated_normal/shape
conv3_3/weights/Initializer/truncated_normal/mean
conv3_3/weights/Initializer/truncated_normal/stddev
conv3_3/weights/Initializer/truncated_normal/TruncatedNormal
conv3_3/weights/Initializer/truncated_normal/mul
conv3_3/weights/Initializer/truncated_normal
conv3_3/weights
conv3_3/weights/Assign
conv3_3/weights/read
conv3_3/weights/Regularizer/l2_regularizer/weight_decay
conv3_3/weights/Regularizer/l2_regularizer/L2Loss
conv3_3/weights/Regularizer/l2_regularizer/value
conv3_3/biases/Initializer/Const
conv3_3/biases
conv3_3/biases/Assign
conv3_3/biases/read
conv3_3/Conv2D
conv3_3/BiasAdd
conv3_3/conv3_3
pool3
conv4_1/weights/Initializer/truncated_normal/shape
conv4_1/weights/Initializer/truncated_normal/mean
conv4_1/weights/Initializer/truncated_normal/stddev
conv4_1/weights/Initializer/truncated_normal/TruncatedNormal
conv4_1/weights/Initializer/truncated_normal/mul
conv4_1/weights/Initializer/truncated_normal
conv4_1/weights
conv4_1/weights/Assign
conv4_1/weights/read
conv4_1/weights/Regularizer/l2_regularizer/weight_decay
conv4_1/weights/Regularizer/l2_regularizer/L2Loss
conv4_1/weights/Regularizer/l2_regularizer/value
conv4_1/biases/Initializer/Const
conv4_1/biases
conv4_1/biases/Assign
conv4_1/biases/read
conv4_1/Conv2D
conv4_1/BiasAdd
conv4_1/conv4_1
conv4_2/weights/Initializer/truncated_normal/shape
conv4_2/weights/Initializer/truncated_normal/mean
conv4_2/weights/Initializer/truncated_normal/stddev
conv4_2/weights/Initializer/truncated_normal/TruncatedNormal
conv4_2/weights/Initializer/truncated_normal/mul
conv4_2/weights/Initializer/truncated_normal
conv4_2/weights
conv4_2/weights/Assign
conv4_2/weights/read
conv4_2/weights/Regularizer/l2_regularizer/weight_decay
conv4_2/weights/Regularizer/l2_regularizer/L2Loss
conv4_2/weights/Regularizer/l2_regularizer/value
conv4_2/biases/Initializer/Const
conv4_2/biases
conv4_2/biases/Assign
conv4_2/biases/read
conv4_2/Conv2D
conv4_2/BiasAdd
conv4_2/conv4_2
conv4_3/weights/Initializer/truncated_normal/shape
conv4_3/weights/Initializer/truncated_normal/mean
conv4_3/weights/Initializer/truncated_normal/stddev
conv4_3/weights/Initializer/truncated_normal/TruncatedNormal
conv4_3/weights/Initializer/truncated_normal/mul
conv4_3/weights/Initializer/truncated_normal
conv4_3/weights
conv4_3/weights/Assign
conv4_3/weights/read
conv4_3/weights/Regularizer/l2_regularizer/weight_decay
conv4_3/weights/Regularizer/l2_regularizer/L2Loss
conv4_3/weights/Regularizer/l2_regularizer/value
conv4_3/biases/Initializer/Const
conv4_3/biases
conv4_3/biases/Assign
conv4_3/biases/read
conv4_3/Conv2D
conv4_3/BiasAdd
conv4_3/conv4_3
pool4
conv5_1/weights/Initializer/truncated_normal/shape
conv5_1/weights/Initializer/truncated_normal/mean
conv5_1/weights/Initializer/truncated_normal/stddev
conv5_1/weights/Initializer/truncated_normal/TruncatedNormal
conv5_1/weights/Initializer/truncated_normal/mul
conv5_1/weights/Initializer/truncated_normal
conv5_1/weights
conv5_1/weights/Assign
conv5_1/weights/read
conv5_1/weights/Regularizer/l2_regularizer/weight_decay
conv5_1/weights/Regularizer/l2_regularizer/L2Loss
conv5_1/weights/Regularizer/l2_regularizer/value
conv5_1/biases/Initializer/Const
conv5_1/biases
conv5_1/biases/Assign
conv5_1/biases/read
conv5_1/Conv2D
conv5_1/BiasAdd
conv5_1/conv5_1
conv5_2/weights/Initializer/truncated_normal/shape
conv5_2/weights/Initializer/truncated_normal/mean
conv5_2/weights/Initializer/truncated_normal/stddev
conv5_2/weights/Initializer/truncated_normal/TruncatedNormal
conv5_2/weights/Initializer/truncated_normal/mul
conv5_2/weights/Initializer/truncated_normal
conv5_2/weights
conv5_2/weights/Assign
conv5_2/weights/read
conv5_2/weights/Regularizer/l2_regularizer/weight_decay
conv5_2/weights/Regularizer/l2_regularizer/L2Loss
conv5_2/weights/Regularizer/l2_regularizer/value
conv5_2/biases/Initializer/Const
conv5_2/biases
conv5_2/biases/Assign
conv5_2/biases/read
conv5_2/Conv2D
conv5_2/BiasAdd
conv5_2/conv5_2
conv5_3/weights/Initializer/truncated_normal/shape
conv5_3/weights/Initializer/truncated_normal/mean
conv5_3/weights/Initializer/truncated_normal/stddev
conv5_3/weights/Initializer/truncated_normal/TruncatedNormal
conv5_3/weights/Initializer/truncated_normal/mul
conv5_3/weights/Initializer/truncated_normal
conv5_3/weights
conv5_3/weights/Assign
conv5_3/weights/read
conv5_3/weights/Regularizer/l2_regularizer/weight_decay
conv5_3/weights/Regularizer/l2_regularizer/L2Loss
conv5_3/weights/Regularizer/l2_regularizer/value
conv5_3/biases/Initializer/Const
conv5_3/biases
conv5_3/biases/Assign
conv5_3/biases/read
conv5_3/Conv2D
conv5_3/BiasAdd
conv5_3/conv5_3
rpn_conv/3x3/weights/Initializer/truncated_normal/shape
rpn_conv/3x3/weights/Initializer/truncated_normal/mean
rpn_conv/3x3/weights/Initializer/truncated_normal/stddev
rpn_conv/3x3/weights/Initializer/truncated_normal/TruncatedNormal
rpn_conv/3x3/weights/Initializer/truncated_normal/mul
rpn_conv/3x3/weights/Initializer/truncated_normal
rpn_conv/3x3/weights
rpn_conv/3x3/weights/Assign
rpn_conv/3x3/weights/read
rpn_conv/3x3/weights/Regularizer/l2_regularizer/weight_decay
rpn_conv/3x3/weights/Regularizer/l2_regularizer/L2Loss
rpn_conv/3x3/weights/Regularizer/l2_regularizer/value
rpn_conv/3x3/biases/Initializer/Const
rpn_conv/3x3/biases
rpn_conv/3x3/biases/Assign
rpn_conv/3x3/biases/read
rpn_conv/3x3/Conv2D
rpn_conv/3x3/BiasAdd
rpn_conv/3x3/rpn_conv/3x3
Shape
Reshape/shape
Reshape
Shape_1
strided_slice/stack
strided_slice/stack_1
strided_slice/stack_2
strided_slice
lstm_o/weights/Initializer/truncated_normal/shape
lstm_o/weights/Initializer/truncated_normal/mean
lstm_o/weights/Initializer/truncated_normal/stddev
lstm_o/weights/Initializer/truncated_normal/TruncatedNormal
lstm_o/weights/Initializer/truncated_normal/mul
lstm_o/weights/Initializer/truncated_normal
lstm_o/weights
lstm_o/weights/Assign
lstm_o/weights/read
lstm_o/weights/Regularizer/l2_regularizer/weight_decay
lstm_o/weights/Regularizer/l2_regularizer/L2Loss
lstm_o/weights/Regularizer/l2_regularizer/value
lstm_o/biases/Initializer/Const
lstm_o/biases
lstm_o/biases/Assign
lstm_o/biases/read
lstm_o/MatMul
lstm_o/add
lstm_o/Const
lstm_o/split/split_dim
lstm_o/split
lstm_o/BasicLSTMCellZeroState/ExpandDims/dim
lstm_o/BasicLSTMCellZeroState/ExpandDims
lstm_o/BasicLSTMCellZeroState/Const
lstm_o/BasicLSTMCellZeroState/concat/axis
lstm_o/BasicLSTMCellZeroState/concat
lstm_o/BasicLSTMCellZeroState/zeros/Const
lstm_o/BasicLSTMCellZeroState/zeros
lstm_o/BasicLSTMCellZeroState/ExpandDims_1/dim
lstm_o/BasicLSTMCellZeroState/ExpandDims_1
lstm_o/BasicLSTMCellZeroState/Const_1
lstm_o/rnn/Shape
lstm_o/rnn/strided_slice/stack
lstm_o/rnn/strided_slice/stack_1
lstm_o/rnn/strided_slice/stack_2
lstm_o/rnn/strided_slice
lstm_o/rnn/rnn/basic_lstm_cell/Const
lstm_o/rnn/rnn/basic_lstm_cell/split/split_dim
lstm_o/rnn/rnn/basic_lstm_cell/split
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/shape
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/min
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/max
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/RandomUniform
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/sub
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform/mul
lstm_o/rnn/basic_lstm_cell/kernel/Initializer/random_uniform
lstm_o/rnn/basic_lstm_cell/kernel
lstm_o/rnn/basic_lstm_cell/kernel/Assign
lstm_o/rnn/basic_lstm_cell/kernel/read
lstm_o/rnn/basic_lstm_cell/bias/Initializer/Const
lstm_o/rnn/basic_lstm_cell/bias
lstm_o/rnn/basic_lstm_cell/bias/Assign
lstm_o/rnn/basic_lstm_cell/bias/read
lstm_o/rnn/rnn/basic_lstm_cell/concat/axis
lstm_o/rnn/rnn/basic_lstm_cell/concat
lstm_o/rnn/rnn/basic_lstm_cell/MatMul
lstm_o/rnn/rnn/basic_lstm_cell/BiasAdd
lstm_o/rnn/rnn/basic_lstm_cell/Const_1
lstm_o/rnn/rnn/basic_lstm_cell/split_1/split_dim
lstm_o/rnn/rnn/basic_lstm_cell/split_1
lstm_o/rnn/rnn/basic_lstm_cell/add/y
lstm_o/rnn/rnn/basic_lstm_cell/add
lstm_o/rnn/rnn/basic_lstm_cell/Sigmoid
lstm_o/rnn/rnn/basic_lstm_cell/mul
lstm_o/rnn/rnn/basic_lstm_cell/Sigmoid_1
lstm_o/rnn/rnn/basic_lstm_cell/Tanh
lstm_o/rnn/rnn/basic_lstm_cell/mul_1
lstm_o/rnn/rnn/basic_lstm_cell/add_1
lstm_o/rnn/rnn/basic_lstm_cell/Tanh_1
lstm_o/rnn/rnn/basic_lstm_cell/Sigmoid_2
lstm_o/rnn/rnn/basic_lstm_cell/mul_2
lstm_o/rnn/rnn/basic_lstm_cell/concat_1/axis
lstm_o/rnn/rnn/basic_lstm_cell/concat_1
lstm_o/strided_slice/stack
lstm_o/strided_slice/stack_1
lstm_o/strided_slice/stack_2
lstm_o/strided_slice
lstm_o/strided_slice_1/stack
lstm_o/strided_slice_1/stack_1
lstm_o/strided_slice_1/stack_2
lstm_o/strided_slice_1
lstm_o/strided_slice_2/stack
lstm_o/strided_slice_2/stack_1
lstm_o/strided_slice_2/stack_2
lstm_o/strided_slice_2
lstm_o/Reshape/shape/3
lstm_o/Reshape/shape
lstm_o/Reshape
Shape_2
Reshape_1/shape
Reshape_1
rpn_bbox_pred/weights/Initializer/truncated_normal/shape
rpn_bbox_pred/weights/Initializer/truncated_normal/mean
rpn_bbox_pred/weights/Initializer/truncated_normal/stddev
rpn_bbox_pred/weights/Initializer/truncated_normal/TruncatedNormal
rpn_bbox_pred/weights/Initializer/truncated_normal/mul
rpn_bbox_pred/weights/Initializer/truncated_normal
rpn_bbox_pred/weights
rpn_bbox_pred/weights/Assign
rpn_bbox_pred/weights/read
rpn_bbox_pred/weights/Regularizer/l2_regularizer/weight_decay
rpn_bbox_pred/weights/Regularizer/l2_regularizer/L2Loss
rpn_bbox_pred/weights/Regularizer/l2_regularizer/value
rpn_bbox_pred/biases/Initializer/Const
rpn_bbox_pred/biases
rpn_bbox_pred/biases/Assign
rpn_bbox_pred/biases/read
rpn_bbox_pred/MatMul
rpn_bbox_pred/add
rpn_bbox_pred/strided_slice/stack
rpn_bbox_pred/strided_slice/stack_1
rpn_bbox_pred/strided_slice/stack_2
rpn_bbox_pred/strided_slice
rpn_bbox_pred/strided_slice_1/stack
rpn_bbox_pred/strided_slice_1/stack_1
rpn_bbox_pred/strided_slice_1/stack_2
rpn_bbox_pred/strided_slice_1
rpn_bbox_pred/strided_slice_2/stack
rpn_bbox_pred/strided_slice_2/stack_1
rpn_bbox_pred/strided_slice_2/stack_2
rpn_bbox_pred/strided_slice_2
rpn_bbox_pred/Reshape/shape/3
rpn_bbox_pred/Reshape/shape
rpn_bbox_pred/Reshape
Shape_3
Reshape_2/shape
Reshape_2
rpn_cls_score/weights/Initializer/truncated_normal/shape
rpn_cls_score/weights/Initializer/truncated_normal/mean
rpn_cls_score/weights/Initializer/truncated_normal/stddev
rpn_cls_score/weights/Initializer/truncated_normal/TruncatedNormal
rpn_cls_score/weights/Initializer/truncated_normal/mul
rpn_cls_score/weights/Initializer/truncated_normal
rpn_cls_score/weights
rpn_cls_score/weights/Assign
rpn_cls_score/weights/read
rpn_cls_score/weights/Regularizer/l2_regularizer/weight_decay
rpn_cls_score/weights/Regularizer/l2_regularizer/L2Loss
rpn_cls_score/weights/Regularizer/l2_regularizer/value
rpn_cls_score/biases/Initializer/Const
rpn_cls_score/biases
rpn_cls_score/biases/Assign
rpn_cls_score/biases/read
rpn_cls_score/MatMul
rpn_cls_score/add
rpn_cls_score/strided_slice/stack
rpn_cls_score/strided_slice/stack_1
rpn_cls_score/strided_slice/stack_2
rpn_cls_score/strided_slice
rpn_cls_score/strided_slice_1/stack
rpn_cls_score/strided_slice_1/stack_1
rpn_cls_score/strided_slice_1/stack_2
rpn_cls_score/strided_slice_1
rpn_cls_score/strided_slice_2/stack
rpn_cls_score/strided_slice_2/stack_1
rpn_cls_score/strided_slice_2/stack_2
rpn_cls_score/strided_slice_2
rpn_cls_score/Reshape/shape/3
rpn_cls_score/Reshape/shape
rpn_cls_score/Reshape
Shape_4
strided_slice_1/stack
strided_slice_1/stack_1
strided_slice_1/stack_2
strided_slice_1
strided_slice_2/stack
strided_slice_2/stack_1
strided_slice_2/stack_2
strided_slice_2
Reshape_3/shape/2
Reshape_3/shape/3
Reshape_3/shape
Reshape_3
Shape_5
strided_slice_3/stack
strided_slice_3/stack_1
strided_slice_3/stack_2
strided_slice_3
Reshape_4/shape/0
Reshape_4/shape
Reshape_4
Softmax
strided_slice_4/stack
strided_slice_4/stack_1
strided_slice_4/stack_2
strided_slice_4
strided_slice_5/stack
strided_slice_5/stack_1
strided_slice_5/stack_2
strided_slice_5
strided_slice_6/stack
strided_slice_6/stack_1
strided_slice_6/stack_2
strided_slice_6
rpn_cls_prob/shape/0
rpn_cls_prob/shape
rpn_cls_prob
Shape_6
strided_slice_7/stack
strided_slice_7/stack_1
strided_slice_7/stack_2
strided_slice_7
strided_slice_8/stack
strided_slice_8/stack_1
strided_slice_8/stack_2
strided_slice_8
Reshape_5/shape/2
Reshape_5/shape/3
Reshape_5/shape
Reshape_5
rois/PyFunc/input_3
rois/PyFunc/input_4
rois/PyFunc/input_5
rois/PyFunc
rois/Reshape/shape
rois/Reshape
save/Const
save/SaveV2/tensor_names
save/SaveV2/shape_and_slices
save/SaveV2
save/control_dependency
save/RestoreV2/tensor_names
save/RestoreV2/shape_and_slices
save/RestoreV2
save/Assign
save/RestoreV2_1/tensor_names
save/RestoreV2_1/shape_and_slices
save/RestoreV2_1
save/Assign_1
save/RestoreV2_2/tensor_names
save/RestoreV2_2/shape_and_slices
save/RestoreV2_2
save/Assign_2
save/RestoreV2_3/tensor_names
save/RestoreV2_3/shape_and_slices
save/RestoreV2_3
save/Assign_3
save/RestoreV2_4/tensor_names
save/RestoreV2_4/shape_and_slices
save/RestoreV2_4
save/Assign_4
save/RestoreV2_5/tensor_names
save/RestoreV2_5/shape_and_slices
save/RestoreV2_5
save/Assign_5
save/RestoreV2_6/tensor_names
save/RestoreV2_6/shape_and_slices
save/RestoreV2_6
save/Assign_6
save/RestoreV2_7/tensor_names
save/RestoreV2_7/shape_and_slices
save/RestoreV2_7
save/Assign_7
save/RestoreV2_8/tensor_names
save/RestoreV2_8/shape_and_slices
save/RestoreV2_8
save/Assign_8
save/RestoreV2_9/tensor_names
save/RestoreV2_9/shape_and_slices
save/RestoreV2_9
save/Assign_9
save/RestoreV2_10/tensor_names
save/RestoreV2_10/shape_and_slices
save/RestoreV2_10
save/Assign_10
save/RestoreV2_11/tensor_names
save/RestoreV2_11/shape_and_slices
save/RestoreV2_11
save/Assign_11
save/RestoreV2_12/tensor_names
save/RestoreV2_12/shape_and_slices
save/RestoreV2_12
save/Assign_12
save/RestoreV2_13/tensor_names
save/RestoreV2_13/shape_and_slices
save/RestoreV2_13
save/Assign_13
save/RestoreV2_14/tensor_names
save/RestoreV2_14/shape_and_slices
save/RestoreV2_14
save/Assign_14
save/RestoreV2_15/tensor_names
save/RestoreV2_15/shape_and_slices
save/RestoreV2_15
save/Assign_15
save/RestoreV2_16/tensor_names
save/RestoreV2_16/shape_and_slices
save/RestoreV2_16
save/Assign_16
save/RestoreV2_17/tensor_names
save/RestoreV2_17/shape_and_slices
save/RestoreV2_17
save/Assign_17
save/RestoreV2_18/tensor_names
save/RestoreV2_18/shape_and_slices
save/RestoreV2_18
save/Assign_18
save/RestoreV2_19/tensor_names
save/RestoreV2_19/shape_and_slices
save/RestoreV2_19
save/Assign_19
save/RestoreV2_20/tensor_names
save/RestoreV2_20/shape_and_slices
save/RestoreV2_20
save/Assign_20
save/RestoreV2_21/tensor_names
save/RestoreV2_21/shape_and_slices
save/RestoreV2_21
save/Assign_21
save/RestoreV2_22/tensor_names
save/RestoreV2_22/shape_and_slices
save/RestoreV2_22
save/Assign_22
save/RestoreV2_23/tensor_names
save/RestoreV2_23/shape_and_slices
save/RestoreV2_23
save/Assign_23
save/RestoreV2_24/tensor_names
save/RestoreV2_24/shape_and_slices
save/RestoreV2_24
save/Assign_24
save/RestoreV2_25/tensor_names
save/RestoreV2_25/shape_and_slices
save/RestoreV2_25
save/Assign_25
save/RestoreV2_26/tensor_names
save/RestoreV2_26/shape_and_slices
save/RestoreV2_26
save/Assign_26
save/RestoreV2_27/tensor_names
save/RestoreV2_27/shape_and_slices
save/RestoreV2_27
save/Assign_27
save/RestoreV2_28/tensor_names
save/RestoreV2_28/shape_and_slices
save/RestoreV2_28
save/Assign_28
save/RestoreV2_29/tensor_names
save/RestoreV2_29/shape_and_slices
save/RestoreV2_29
save/Assign_29
save/RestoreV2_30/tensor_names
save/RestoreV2_30/shape_and_slices
save/RestoreV2_30
save/Assign_30
save/RestoreV2_31/tensor_names
save/RestoreV2_31/shape_and_slices
save/RestoreV2_31
save/Assign_31
save/RestoreV2_32/tensor_names
save/RestoreV2_32/shape_and_slices
save/RestoreV2_32
save/Assign_32
save/RestoreV2_33/tensor_names
save/RestoreV2_33/shape_and_slices
save/RestoreV2_33
save/Assign_33
save/RestoreV2_34/tensor_names
save/RestoreV2_34/shape_and_slices
save/RestoreV2_34
save/Assign_34
save/RestoreV2_35/tensor_names
save/RestoreV2_35/shape_and_slices
save/RestoreV2_35
save/Assign_35
save/restore_all

**Comment by wanghuok** [comment]
@eragonruan I solved it. I freeze the model variables that ahead  node 'rois/PyFunc/input_3'.
I specify the output nodes are 'Reshape_5' and 'rpn_bbox_pred/Reshape'.

**Comment by joyJZhang** [comment]
@wanghuok hello,i freeze the model,and then use it.But I find some errors.
UnknownError (see above for traceback): **KeyError: 'pyfunc_0'**
	 [[Node: rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_2/_15, rpn_bbox_pred/Reshape_1/_17, _arg_Placeholder_1_0_1, rois/PyFunc/input_3, rois/PyFunc/input_4, rois/PyFunc/input_4)]]
	 [[Node: rois/PyFunc/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_454_rois/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by ajinkya933** [comment]
@wanghuok what are you trying to say, how did you run the pb file ??

**Comment by ZHUTAO142857** [comment]
> @eragonruan I solved it. I freeze the model variables that ahead node 'rois/PyFunc/input_3'.
> I specify the output nodes are 'Reshape_5' and 'rpn_bbox_pred/Reshape'.

Hello, I use 'Reshape_5' and 'rpn_bbox_pred/Reshape' as name node just like what you say and I've export a pb file. But I don't know how to test the pb file. Can you please give me some advice?
