### ISSUE TITLE
Can you provide the training dataset?

### ISSUE THREAD

**Issue by mymynew** [eragonruan/text-detection-ctpn#4]
我也在看CTPN的论文和代码，但是对其数据标注和Side-refinement部分一直不清楚它是怎么做的。

**Comment by eragonruan** [comment]
You can download from google [drive](https://drive.google.com/open?id=0B_WmJoEtfQhDRl82b1dJTjB2ZGc)

**Comment by cjt222** [comment]
could you tell me how to train model with your data?

**Comment by cjt222** [comment]
@eragonruan

**Comment by eragonruan** [comment]
@cjt222 put VGG_imagenet.npy in data/pretrain/, put VOCdevkit in data/
```shell
cd data
ln -s VOCdevkit VOCdevkit2007
```
,then just run python ./ctpn/train_net.py in the root

**Comment by cjt222** [comment]
Thank you so much，I have try it successfully！！！And I still have a question :Could you tell me where I can get Chinese dataset like ID card and so on? Maybe Chinese dataset is poor on Internet.

**Comment by eragonruan** [comment]
@cjt222 the dataset I use is multi-lingual scene text detection dataset, you can find it [here](http://rrc.cvc.uab.es/?ch=8&com=introduction). There are about 800 images are chinses. I used all images in this dataset except arabic images.

**Comment by cjt222** [comment]
OK, I see.Thank you so much!!!  And if I want to caclulate the precision of model, can I copy the code of MAP of faster rcnn in caffe? Or whether tensorflow has this function or not? Thank you very much for your answer

**Comment by eragonruan** [comment]
You have to implement this part yourself, it seems that the origin repo did not provide code of this part, or you can found it in this [repo](https://github.com/lufo816/object_detection_mAP).

**Comment by cjt222** [comment]
OK，I see，Thank you so much!!! @eragonruan

**Comment by cjt222** [comment]
Exuse me,I am sorry to bother you again. But I meet a problem that I do not understand when I train model on MLT.

voc_2007_trainval gt roidb loaded from /root/chengjuntao/text-detection-ctpn/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
Traceback (most recent call last):
  File "ctpn/train_net.py", line 27, in <module>
    roidb = get_training_roidb(imdb)
  File "/root/chengjuntao/text-detection-ctpn/lib/fast_rcnn/train.py", line 249, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/root/chengjuntao/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 32, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range
In fact, I do not know why it is out of range when the boundingboxs are too many, can you explain it for me? Thank you so  much!! @ @eragonruan

**Comment by cjt222** [comment]
I have known the solution !!! Thank you!!!

**Comment by wanghaisheng** [comment]
how to prepare my own training data and annotate them for this tools?

**Comment by wanghaisheng** [comment]
do u know any existing GUI tool i can use to manually label original image to get the ground  truth txt

**Comment by cjt222** [comment]
I want to change test code from python2 to python3, but when i run python3 ctpn/demo.y,  it caused 
"ImportError: No module named 'fast_rcnn'", in fact, i have make in lib by python3, do you know where i am wrong? thank you so   @@!!much

**Comment by cjt222** [comment]
@eragonruan

**Comment by eragonruan** [comment]
@wanghaisheng you Can label the image by this [repo](https://github.com/tzutalin/labelImg)

**Comment by eragonruan** [comment]
@cjt222 you have to change the import path due to the differences between python2 and 3
