### ISSUE TITLE
Problem with CPU model

### ISSUE THREAD

**Issue by zhao181** [eragonruan/text-detection-ctpn#40]
Hi author,thanks. I have only a cpu and want to run the demo.py.
According to the README.m, it seems that, in CPU mode, we need to
do the following two things before running:
(a) Set USE_GPU_NMS=False in ctpn/text.yml;
(b) Execute chmod +x make.sh  and  ./make.sh in the directory lib/utils.
Is this right?

However, when I run the command  ./make.sh, it complains as follows:
=========================================================
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 26, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
mv: cannot stat 'utils/*': No such file or directory
==============================================================
Then what should I do to run the demo with only a CPU? 

 I have been struck for a whole day.   I am looking forward to your reply.

**Comment by eragonruan** [comment]
@zhao181 you have to modify setup.py first. 
```python
from Cython.Build import cythonize
import numpy as np
from distutils.core import setup

try:
    numpy_include = np.get_include()
except AttributeError:
    numpy_include = np.get_numpy_include()

setup(
    ext_modules=cythonize(["bbox.pyx","cython_nms.pyx"],include_dirs=[numpy_include]),
)
```
runpython setup.py build， then copy .so in build to lib/utils
for more detail, see this [issue](https://github.com/eragonruan/eragonruan.github.io/issues/2)

**Comment by zhao181** [comment]
Deal author,
Thanks for your help. But when I run "python setup.py build"，there comes the error as follows:
===========================================
D:\cpu\text-detection-ctpn-master\lib\utils>python setup.py build
('numpy_include', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\numpy\\core\\include')
C:\ProgramData\Anaconda2\lib\site-packages\Cython\Compiler\Main.py:562: UserWarning: got unknown compilation option, please remove: include_dirs
  warnings.warn(message)
running build
running build_ext
building 'lib.utils.bbox' extension
C:\ProgramData\Anaconda2\MinGW\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -IC:\ProgramData\Anaconda2\include -IC:\ProgramData\Anaconda2\PC -c bbox.c -o build\temp.win-amd64-2.7\Release\bbox.o
bbox.c:274:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
error: command 'C:\\ProgramData\\Anaconda2\\MinGW\\bin\\gcc.exe' failed with exit status 1
===============================================
I test both under ubuntu and windows, this problem always exists. It seems that the parameter "include_dirs" in the following code does not work,
ext_modules=cythonize(["bbox.pyx","cython_nms.pyx"],include_dirs=[numpy_include]),

I have added "print(include_dirs)" before this sentence, and find the numpy include directory is correct.

Can you offer further help? I will appreciate your for that. Thanks in adavance.

**Comment by zhao181** [comment]
I am looking forward to your reply.

**Comment by eragonruan** [comment]
@zhao181 reduce your cython version to 0.24, high version cython do not have the include_dir option

**Comment by Jinkeycode** [comment]
use cython0.24 still error：

fatal error: 'numpy/arrayobject.h' file not found

**Comment by eragonruan** [comment]
[andersbll/cudarray/issues/25](https://github.com/andersbll/cudarray/issues/25)
