### ISSUE TITLE
How do i crop text areas detected by CTPN?

### ISSUE THREAD

**Issue by akshadaas** [eragonruan/text-detection-ctpn#400]

**Comment by akshadaas** [comment]
@eragonruan Can you help me?

**Comment by maky-hnou** [comment]
@akshadaas , after running [demo.py](https://github.com/eragonruan/text-detection-ctpn/blob/banjin-dev/main/demo.py), for every image, a text file is created wich contains the coordinates of every text zone detected.  
You can simply read the coordinates from the text_file (each text file has the same name as the image treated) then use opencv for example to crop the text zones.
Example of the text file (its names is for example `img1.txt`) containing the coordinates:  
```
61,237,246,270
61,558,143,579
61,581,164,598
```
Here is the code :  
```
import cv2

img = cv2.imread('path_to_your_image'):
with open('path_to_your_text_file.txt', 'r') as foo:
    index = 0
    # Iterate over every line in the text file 
    for line in foo:
        # Get the list of the coordinates from the line
        coords_list = line.strip().split(',')
        # Convert the list of strings to list of ints
        coords = list(map(int, coords_list))
        # Set the coords
        xmin = coords[0]
        xmax = coords[2]
        ymin = coords[1]
        ymax = coords[3]
        # Crop the zone from the image
        cv2.imwrite('zone_.jpg'.format(index), img[ymin:ymax, xmin:xmax])
        index += 1
foo.close()
```

**Comment by akshadaas** [comment]
after demo.py, the img.txt file contains 8 coordinates with score at end. When i run your code, zone.jpg stored as txt file. Something wrong is happened

**Comment by maky-hnou** [comment]
@akshadaas I think @eragonruan  made some changes since the last time I used the code. Would you please post an example of the img.txt file content so that I understand how to deal with it?

**Comment by akshadaas** [comment]
Actually I dont understand why do we need 8 coordinates? Can you please explain that thing also?

Here is the img.txt contents:

176,138,432,138,432,153,176,153,0.9963368
336,264,544,264,544,284,336,284,0.99602354
64,178,432,178,432,197,64,197,0.99598503
64,210,448,210,448,229,64,229,0.9959632
64,318,320,318,320,339,64,339,0.9958841
64,235,288,235,288,253,64,253,0.9958134
64,288,288,288,288,306,64,306,0.9957832
64,427,352,427,352,446,64,446,0.995691
64,346,528,346,528,361,64,361,0.9955764
64,399,368,399,368,418,64,418,0.99550974
64,370,256,370,256,387,64,387,0.99547845
64,455,368,455,368,470,64,470,0.99547404
64,260,288,260,288,278,64,278,0.9954098

**Comment by maky-hnou** [comment]
@akshadaas , Normally we don't need to 8 coordinates to draw a bound box.  
As in [this line](https://github.com/eragonruan/text-detection-ctpn/blob/0acfdeb48b3a741817a674a32ab4e4cb3c39cb99/utils/text_connector/detectors.py#L42), the coordinates with indexes (1, 3, 5, 7) represent the heights (the y coordinates) of the points.  
And as in [this line](https://github.com/eragonruan/text-detection-ctpn/blob/0acfdeb48b3a741817a674a32ab4e4cb3c39cb99/utils/text_connector/detectors.py#L43), the coordinates with indexes(0, 2, 4, 6) represent the widths (the x coordinates) of the points.  
Let's take the first line of the text file as an example:  
176,138,432,138,432,153,176,153,0.9963368.   
So we have A(176, 138), B(432, 138), C(432, 153) and D(176, 153).  
To crop the image, we only need two points which are A and C.
So the code would be:  
```
import cv2

img = cv2.imread('path_to_your_image'):
with open('path_to_your_text_file.txt', 'r') as foo:
    index = 0
    # Iterate over every line in the text file 
    for line in foo:
        # Get the list of the coordinates from the line
        coords_list = line.strip().split(',')[:-1]
        # Convert the list of strings to list of ints
        coords = list(map(int, coords_list))
        # Set the coords
        xmin = coords[0]
        xmax = coords[4]
        ymin = coords[1]
        ymax = coords[5]
        # Crop the zone from the image
        cv2.imwrite('zone_{}.jpg'.format(index), img[ymin:ymax, xmin:xmax])
        index += 1
foo.close()
```

**Comment by akshadaas** [comment]
@maky-hnou  Thank you so much. But  I want to set the coordinates such that it can crops words. what are the changes I have to do?

**Comment by akshadaas** [comment]
I think i have to set a threshold.

**Comment by maky-hnou** [comment]
@akshadaas , well for the words, I have no idea. I think that CTPN detects a whole text zone, not words.
Porbably @eragonruan is the best one to answer you about your question.  
I also suggest that you take a look at this [post](https://www.pyimagesearch.com/2018/08/20/opencv-text-detection-east-text-detector/), may be you'll find it useful.

**Comment by akshadaas** [comment]
Thanks a lot for your help.
