### ISSUE TITLE
ValueError: Protocol message RunOptions has no "report_tensor_allocations_upon_oom" field.

### ISSUE THREAD

**Issue by phybrain** [eragonruan/text-detection-ctpn#409]
When running train_net.py, it throws this exception：
` File "ctpn/train_net.py", line 54, in <module>
    restore=True)
  File "/home/xxx/text-detection-ctpn/lib/fast_rcnn/train.py", line 245, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "/home/xxx/text-detection-ctpn/lib/fast_rcnn/train.py", line 178, in train_model
    run_options = tf.RunOptions(report_tensor_allocations_upon_oom=True)   
ValueError: Protocol message RunOptions has no "report_tensor_allocations_upon_oom" field.
`

**Comment by XinyingZheng** [comment]
so, how to fix this problem, have you sloved this error?
