### ISSUE TITLE
how to deal with skew box

### ISSUE THREAD

**Issue by cjt222** [eragonruan/text-detection-ctpn#41]
hello, i saw your blog and  you optimize CTPN so that it can detect skew words, but i want to know if you add a angle in loss function, how do you deal groundtruh？are you dividing groundtruth into small box in sknew direction? @eragonruan

**Comment by eragonruan** [comment]
@cjt222 you can modify according to this [paper](https://arxiv.org/abs/1703.06520) if you wanna to use ctpn to detect oriented text
