### ISSUE TITLE
any Labeling tool for creating the dataset?

### ISSUE THREAD

**Issue by BarCodeReader** [eragonruan/text-detection-ctpn#417]
I need some tool which can return me bounding box coordinates...
any idea?

thanks in advance.

**Comment by mohitjain1943** [comment]
Hi @BarCodeReader did you got any tool to create dataset

**Comment by BarCodeReader** [comment]
> Hi @BarCodeReader did you got any tool to create dataset

there are some tools made for YOLO, you can search for it, clone it from github and use it.

for example: https://github.com/YongWookHa/yolo-labeling-tool
