### ISSUE TITLE
谁能远程教我怎么运行这个项目，有偿

### ISSUE THREAD

**Issue by beijing-penguin** [eragonruan/text-detection-ctpn#418]
如题。联系本人QQ525196223

**Comment by BarCodeReader** [comment]
啥子都不会玩几把玩，伸手党。

**Comment by beijing-penguin** [comment]
> 啥子都不会玩几把玩，伸手党。

不是， 报了 一个 我看不懂的错误，小白一个，弄不动了。。而且时间紧，也着急，这是最快的办法。大神如果有空，抽空 帮个忙。感激不尽。

**Comment by beijing-penguin** [comment]
> 啥子都不会玩几把玩，伸手党。

我花钱 请人帮忙，到时候 再把问题免费 公开出来，请问，哪里不合适？

**Comment by Ysnower** [comment]
花钱请人帮忙没啥毛病
