### ISSUE TITLE
ima_3208.jpg does not have gt.txt

### ISSUE THREAD

**Issue by BarCodeReader** [eragonruan/text-detection-ctpn#420]
@eragonruan 

Hi,

firstly, thanks for your work and this repo.
I installed successfully and ran it smoothly, for both your dataset and my own dataset. the result is very robust.

during my regular file checking..i found that for your dataset, which is 'mlt' from google drive, img_3208.jpg does not have its gt.txt file in the lable folder.

so I suggest either remove that img or add the txt.

best regards

**Comment by riyana23** [comment]
Hi @BarCodeReader ,
For how many iterations did you train?
Do you have any idea when the training should be stopped ?

**Comment by BarCodeReader** [comment]
> Hi @BarCodeReader ,
> For how many iterations did you train?
> Do you have any idea when the training should be stopped ?

i train 80K iter, and load all .ckpt to evaluate the IOU or whatever metrics you use and select the best one.

**Comment by riyana23** [comment]
How many images were there in your data set and what kind of images?
