### ISSUE TITLE
I have the same question when training, how to solve it?

### ISSUE THREAD

**Issue by sxp0100** [eragonruan/text-detection-ctpn#423]
if your error is like"IllegalFlagValueError: flag --decay_rate=0.1: Expect argument to be a string or int, found <class 'float'>",try change "tf.app.flags.DEFINE_integer('decay_rate', 0.1, '')"into"tf.app.flags.DEFINE_float('decay_rate', 0.1, '')" in train.py

**Comment by Mrlei-go** [comment]
I just change 'integer' into 'float'
