### ISSUE TITLE
How To Setting Training Data Question

### ISSUE THREAD

**Issue by Wangweilai1** [eragonruan/text-detection-ctpn#44]
Excuse me, Sorry, I'm a green hand, When I use this program, I don't know How to Setting Training Data, When I follow  "Prepare" Step, I didn't found the Training Data in "Baidu Yun", Can you tell me where the Training Data (what's link I can got the Training Data) or How to i can Set the Training Data?

**Comment by eragonruan** [comment]
in baiduyun， VOCdevkit.zip contains the training data

**Comment by Wangweilai1** [comment]
The VOCdevkit\VOC2007\Annotations directory is all of *.xml (img_1001.xml ...)file, but in split_label.py  
`
for file in files:
    _, basename = os.path.split(file)
    if basename.lower().split('.')[-1] not in ['jpg', 'png']:
        continue
    stem, ext = os.path.splitext(basename)
    **gt_file = os.path.join(gt_path, 'gt_' + stem + '.txt')**
    img_path = os.path.join(path, file)
    print(img_path)
    img = cv.imread(img_path)
    img_size = img.shape
    im_size_min = np.min(img_size[0:2])
    im_size_max = np.max(img_size[0:2])

    im_scale = float(600) / float(im_size_min)
    if np.round(im_scale * im_size_max) > 1200:
        im_scale = float(1200) / float(im_size_max)
    re_im = cv.resize(img, None, None, fx=im_scale, fy=im_scale, interpolation=cv.INTER_LINEAR)
    re_size = re_im.shape
    cv.imwrite(os.path.join(out_path, stem) + '.jpg', re_im)

    with open(gt_file, 'r') as f:
        **lines = f.readlines()**
    for line in lines:
`
gt_file = os.path.join(gt_path, 'gt_' + stem + '.txt') is mean that the annotations is *.txt file.
so When I run zhe split_label.py it can't find gt_img_1001.txt File?

**Comment by eragonruan** [comment]
@Wangweilai1 the data I provided has been prepared well. just put it in data/ and run `ln -s TEXTVOC VOCdevkit2007`, then buid the library and start training

**Comment by Wangweilai1** [comment]
OK, I got it, Thanks for you help.
