### ISSUE TITLE
can not detect anything

### ISSUE THREAD

**Issue by jsxyzb** [eragonruan/text-detection-ctpn#45]
I used your lasted codes and your data, but it can't convergence at all. Please tell me why?

**Comment by jsxyzb** [comment]
'"Not convergence", I mean it can detect nothing.

**Comment by eragonruan** [comment]
@jsxyzb try set [MAX_HORIZONTAL_GAP](https://github.com/eragonruan/text-detection-ctpn/blob/1bb8e762bff67bf89fd635507ed105321b92f9a3/ctpn/cfg.py#L2) to 60 or 70
