### ISSUE TITLE
how to get detected text from text-detection-ctpn?. 

### ISSUE THREAD

**Issue by muthuramanm** [eragonruan/text-detection-ctpn#453]
it gave us bbox's. what should i do to get original text from bbox?.please share your suggestions.
i'm getting bbox values like below,
160,509,592,509,592,577,160,577,0.9996464
128,400,384,400,384,466,128,466,0.99963737
96,606,607,606,607,680,96,680,0.9996295
256,194,464,194,464,254,256,254,0.99961853
272,305,560,305,560,369,272,369,0.99960893
112,79,432,79,432,145,112,145,0.999607
64,0,176,0,176,16,64,16,0.99959356
256,0,320,0,320,18,256,18,0.99959296

**Comment by maky-hnou** [comment]
@muthuramanm the values you got represent the bounding boxes coordinates plus the scores/probabilities of those boxes containing text or not.  
Suppose that the coordinates are as follows: x1, y1, x2, y2, x3, y3, x4, y4, score
To crop the text zones, you do for example:
  
`text1 = img[y1:y4, x1:x4]`  
I am not sure about the order of the coordinates. But it is something close to what I wrote above.  
If you want to read the text, I suggest you use Tesseract (Pytesseract for Python).

**Comment by Tetsujinfr** [comment]
If you want the text in string format uses a text recognition algo on top of this ones, like [Deep Text Recognition Benchmark](https://github.com/clovaai/deep-text-recognition-benchmark)  .
If you want to do everything (text detection and recognition) with in one model pass, use another algo like [Conv CharNet](https://github.com/MalongTech/research-charnet)  (but it is a bit slow and memory intensive).
I think you can close this issue.
