### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by zhao181** [eragonruan/text-detection-ctpn#46]
Dear author, could you add some summaries to the code so that the details of model structure and dataflow could be visualized in a tensorboard? We think it will help a lot. Thanks.

**Comment by eragonruan** [comment]
@zhao181 sorry, I didn't catch you. The graph will be generated by tf by default when you train the model. what kind of summaries did you mean

**Comment by zhao181** [comment]
@eragonruan  Hi author, would you please establish a qq group so that we can discuss the code directly? I am recently reading the paper and the code. It proves to be so difficult. My QQ is 3125505517.

**Comment by eragonruan** [comment]
I seldom use qq currently. so, just use issue or you can leave a message in my blog if you wanna use chinese.

**Comment by zhao181** [comment]
Ok, thanks.
