### ISSUE TITLE
Did you train your model on a Chinese database?

### ISSUE THREAD

**Issue by houxiaoxia1** [eragonruan/text-detection-ctpn#53]
@eragonruan  Hi, Thank you for your sharing. I have a question. Did you train your model on a Chinese database? I tested your model on some pictures with Chinese and it did a good job. Could you tell me which one database you chose and how to get it? Thank you very much.

**Comment by eragonruan** [comment]
@houxiaoxia1 I used the multi-lingual scene text dataset for training. you can download it from [here](http://rrc.cvc.uab.es/?ch=8&com=downloads)

**Comment by houxiaoxia1** [comment]
@eragonruan Thank you.

**Comment by houxiaoxia1** [comment]
Excause me, is it possible to do a batch test? I mean more than two pictures are input to the test net. Thank you.

**Comment by eragonruan** [comment]
@houxiaoxia1 Theoretically speaking, yes. But  I'm not sure if there's bugs exist.

**Comment by apple1987** [comment]
download MLT dataset failed, always require me to registerit , but i have register for 3times.
