### ISSUE TITLE
saving intermediate checkpoint

### ISSUE THREAD

**Issue by JiteshPshah** [eragonruan/text-detection-ctpn#57]
HI, 
Is your code saving the intermediate checkpoints ? if no how to do I add the code for it ?

**Comment by eragonruan** [comment]
@JiteshPshah yes, your can modify this parameter in  [/ctpn/text.yml](https://github.com/eragonruan/text-detection-ctpn/blob/5d091787c9ba2e0c5da919341a9fe11117cceab2/ctpn/text.yml#L17), currently, i save the model every 1k steps

**Comment by JiteshPshah** [comment]
@eragonruan  Thanks Buddy ....
