### ISSUE TITLE
Total Loss is so much fluctuating 

### ISSUE THREAD

**Issue by JiteshPshah** [eragonruan/text-detection-ctpn#58]
Hi, Why the total loss is so much high in initial and fluctuating in further iterations ? I have used the data of handwritten text records to crop the individual blocks of handwritten text.

**Comment by eragonruan** [comment]
@JiteshPshah high?How much is  the data. In my experiments, in initial, cls loss is about 1~2 and reg loss is about 1.

**Comment by JiteshPshah** [comment]
It is in range of 6 to 15 and reg loss box is in between 3 to 4 , I have only one class and 1147 Images.

**Comment by eragonruan** [comment]
try check the annotation after split_label, see whether everything is ok. Also, can the model converge or just fluctuating?
