### ISSUE TITLE
ImportError: cannot import name 'bbox'

### ISSUE THREAD

**Issue by GeneralJing** [eragonruan/text-detection-ctpn#59]
运行demo的时候提示不能导入，Google了很多也没能解决问题，求助

**Comment by eragonruan** [comment]
- have you build the library sucessfully?
- did you run demo in the root directory?
- you should provide more detail

**Comment by GeneralJing** [comment]
我在运行demo的时候，提示报错，具体位置是：
  File "D:/work/text-detection-ctpn-master/ctpn/demo.py", line 9, in <module>
    from lib.networks.factory import get_network
  File "..\lib\__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "..\lib\fast_rcnn\__init__.py", line 2, in <module>
    from . import train
  File "..\lib\fast_rcnn\train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "..\lib\roi_data_layer\__init__.py", line 1, in <module>
    from . import roidb
  File "..\lib\roi_data_layer\roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "..\lib\utils\__init__.py", line 4, in <module>
    from . import bbox
ImportError: cannot import name 'bbox'
百度谷歌了很多，这个是fastrnn下面需要依赖的文件吗？我看文件夹下面只有.c跟.pyx文件，没有对应的.py文件，这个是怎么使用呢？刚接触这一块，所以不是很了解，报错的__init__.py文件还引用了cython_nms，gpu_nms，这三个都应该先编译才能使用吗？那怎么样编译呢？我只查到一个博客说是在编译后产生.so文件，这是在Linux下使用的文件吧如果在Windows下如何正确导入？
我本地的环境是Windows10 Spyder，我的qq是1501226581，想跟您详细请教下。

**Comment by cailiang9** [comment]
`cd lib/utils/ && python setup.py build && cp build/lib.linux-x86_64-3.6/lib/utils/*.so ./
`
For cpu version, you can refer modifications of setup.py: https://github.com/cailiang9/text-detection-ctpn/commit/fa794637ee76485d77d340af48ccf68bb3cdd207

**Comment by chengming1108** [comment]
> 我在运行demo的时候，提示报错，具体位置是： File "D:/work/text-detection-ctpn-master/ctpn/demo.py", line 9, in from lib.networks.factory import get_network File "..\lib__init__.py", line 1, in from . import fast_rcnn File "..\lib\fast_rcnn__init__.py", line 2, in from . import train File "..\lib\fast_rcnn\train.py", line 5, in from ..roi_data_layer.layer import RoIDataLayer File "..\lib\roi_data_layer__init__.py", line 1, in from . import roidb File "..\lib\roi_data_layer\roidb.py", line 5, in from lib.utils.bbox import bbox_overlaps File "..\lib\utils__init__.py", line 4, in from . import bbox ImportError: cannot import name 'bbox' 百度谷歌了很多，这个是fastrnn下面需要依赖的文件吗？我看文件夹下面只有.c跟.pyx文件，没有对应的.py文件，这个是怎么使用呢？刚接触这一块，所以不是很了解，报错的__init__.py文件还引用了cython_nms，gpu_nms，这三个都应该先编译才能使用吗？那怎么样编译呢？我只查到一个博客说是在编译后产生.so文件，这是在Linux下使用的文件吧如果在Windows下如何正确导入？ 我本地的环境是Windows10 Spyder，我的qq是1501226581，想跟您详细请教下。

您好请问你解决了吗。想加一下您QQ详细问一下教程
