### ISSUE TITLE
split_label.py deal with .txt but .xml provided in VOC2007, and import python_nms error in demo

### ISSUE THREAD

**Issue by BrownOfSummer** [eragonruan/text-detection-ctpn#6]

**Comment by eragonruan** [comment]
most scene text dataset like icdar，msra-td500，coco-text，labels are provided with .txt. because I implement this repo based on the faster rcnn framework provided by r.b.g., hence have to convert the training data into voc format. 
Import error？ can you provide more detail?

**Comment by BrownOfSummer** [comment]
File "./ctpn/demo.py", line 9, in <module>
    from lib.networks.factory import get_network
  File "/text-detection-ctpn/lib/__init__.py", line 1, in <module>
    import fast_rcnn
  File "/text-detection-ctpn/lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/text-detection-ctpn/lib/fast_rcnn/train.py", line 6, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/text-detection-ctpn/lib/roi_data_layer/__init__.py", line 7, in <module>
    import roidb
  File "/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 19, in <module>
    from ..utils.cython_bbox import bbox_overlaps
  File "/text-detection-ctpn/lib/utils/__init__.py", line 7, in <module>
    **from . import cython_nms**
ImportError: cannot import name cython_nms

**I figured the error, I should do "make" in ./libs to get python_nums for import;**

But when I do **make**, another error occurs:
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**So, your work cannot work without CUDA and GPU? CPU only could not work?**

**Comment by eragonruan** [comment]
you can comment out `from . import cython_nms` in lib/utils/__init__.py
since I did not use cython or gpu version NMS. 
if you wanna to use nms implement in cython, you have to modify some parameter in setup.py to suit your environment.

**Comment by BrownOfSummer** [comment]
That is not the solution, more errors occurred when just comment it up.
(1) I think you should check your ./lib/, some file may missing, such as "**make.sh**" called in Makefile.
(2) Can your code run on the CPU only machine without CUDA ?

**Comment by eragonruan** [comment]
@BrownOfSummer I have fixed it. you can follow readme to build nms. If anything wrong, feel free to contact

**Comment by BrownOfSummer** [comment]
@eragonruan Thanks a lot, the make.sh works fine for me !  Demo run successfully in tensorflow1.0 but failed in tensorflow1.2, but never mind.
But when I train the network,  **RuntimeError: Graph is finalized and cannot be modified.**
 I opened a new issue !
