### ISSUE TITLE
Invalid argument: ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by bhangaboy** [eragonruan/text-detection-ctpn#62]
Hi I am getting the following error while training on my own data set. 
I am running this code on ubuntu 17.04 only cpu 8gb ram.
To ensure that every image has correct bounding box i re run this code with only handly picked 20 images.

This is the whole error

Using config:
{'ANCHOR_SCALES': [16],
 'DATA_DIR': '/home/choice/new-text-detection-ctpn/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'ctpn_end2end',
 'GPU_ID': 0,
 'IS_EXTRAPOLATING': True,
 'IS_MULTISCALE': False,
 'IS_RPN': True,
 'LOG_DIR': 'ctpn',
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/choice/new-text-detection-ctpn/models/pascal_voc',
 'NCLASSES': 1,
 'NET_NAME': 'VGGnet',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'REGION_PROPOSAL': 'RPN',
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/manish/new-text-detection-ctpn',
 'SUBCLS_NAME': 'voxel_exemplars',
 'TEST': {'BBOX_REG': True,
          'DETECT_MODE': 'O',
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 8,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 1000,
          'RPN_PRE_NMS_TOP_N': 12000,
          'SCALES': [600],
          'SVM': False,
          'checkpoints_path': 'checkpoints/'},
 'TRAIN': {'ASPECTS': [1],
           'ASPECT_GROUPING': True,
           'BATCH_SIZE': 300,
           'BBOX_INSIDE_WEIGHTS': [0, 1, 0, 1],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'DISPLAY': 10,
           'DONTCARE_AREA_INTERSECTION_HI': 0.5,
           'FG_FRACTION': 0.3,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'KERNEL_SIZE': 5,
           'LEARNING_RATE': 1e-05,
           'LOG_IMAGE_ITERS': 100,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'OHEM': False,
           'PRECLUDE_HARD_SAMPLES': True,
           'PROPOSAL_METHOD': 'gt',
           'RANDOM_DOWNSAMPLE': False,
           'RPN_BATCHSIZE': 300,
           'RPN_BBOX_INSIDE_WEIGHTS': [1, 1, 1, 1],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SCALES_BASE': [0.25, 0.5, 1.0, 2.0, 3.0],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 1000,
           'SNAPSHOT_PREFIX': 'VGGnet_fast_rcnn',
           'SOLVER': 'Adam',
           'STEPSIZE': 70000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False,
           'WEIGHT_DECAY': 0.0005,
           'restore': 0},
 'USE_GPU_NMS': False}
<bound method imdb.default_roidb of <lib.datasets.pascal_voc.pascal_voc object at 0x7fba9c52e4e0>>
Loaded dataset `voc_2007_trainval` for training
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/choice/new-text-detection-ctpn/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
Output will be saved to `/home/manish/new-text-detection-ctpn/output/ctpn_end2end/voc_2007_trainval`
Logs will be saved to `/home/manish/new-text-detection-ctpn/logs/ctpn/voc_2007_trainval/2017-12-13-16-54-41`
/gpu:0
Tensor("data:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("im_info:0", shape=(?, 3), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("gt_boxes:0", shape=(?, 5), dtype=float32)
Tensor("gt_ishard:0", shape=(?,), dtype=int32)
Tensor("dontcare_areas:0", shape=(?, 4), dtype=float32)
Tensor("im_info:0", shape=(?, 3), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
2017-12-13 16:54:42.227266: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Computing bounding-box regression targets...
bbox target means:
[[ 0.  0.  0.  0.]]
/home/manish/new-text-detection-ctpn/lib/roi_data_layer/roidb.py:86: RuntimeWarning: Mean of empty slice.
  print(means[1:, :].mean(axis=0)) # ignore bg class
/home/manish/.local/lib/python3.5/site-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
[ nan  nan  nan  nan]
bbox target stdevs:
[[ 0.1  0.1  0.2  0.2]]
/home/manish/new-text-detection-ctpn/lib/roi_data_layer/roidb.py:89: RuntimeWarning: Mean of empty slice.
  print(stds[1:, :].mean(axis=0)) # ignore bg class
[ nan  nan  nan  nan]
Normalizing targets
done
Solving...
/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading pretrained model weights from data/pretrain/VGG_imagenet.npy
assign pretrain model biases to conv2_2
assign pretrain model weights to conv2_2
assign pretrain model biases to conv4_2
assign pretrain model weights to conv4_2
assign pretrain model biases to conv4_1
assign pretrain model weights to conv4_1
assign pretrain model biases to conv1_2
assign pretrain model weights to conv1_2
ignore fc6
ignore fc6
assign pretrain model biases to conv3_3
assign pretrain model weights to conv3_3
assign pretrain model biases to conv5_2
assign pretrain model weights to conv5_2
assign pretrain model biases to conv3_2
assign pretrain model weights to conv3_2
assign pretrain model biases to conv3_1
assign pretrain model weights to conv3_1
assign pretrain model biases to conv1_1
assign pretrain model weights to conv1_1
assign pretrain model biases to conv5_3
assign pretrain model weights to conv5_3
assign pretrain model biases to conv4_3
assign pretrain model weights to conv4_3
ignore fc8
ignore fc8
assign pretrain model biases to conv2_1
assign pretrain model weights to conv2_1
ignore fc7
ignore fc7
assign pretrain model biases to conv5_1
assign pretrain model weights to conv5_1
2017-12-13 16:54:57.866230: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: ValueError: attempt to get argmax of an empty sequence
Traceback (most recent call last):
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmax of an empty sequence
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/Reshape_1, _arg_gt_boxes_0_3, _arg_gt_ishard_0_4, _arg_dontcare_areas_0_2, _arg_im_info_0_5, rpn-data/PyFunc/input_5, rpn-data/PyFunc/input_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ctpn/train_net.py", line 37, in <module>
    restore=bool(int(cfg.TRAIN.restore)))
  File "/home/manish/new-text-detection-ctpn/lib/fast_rcnn/train.py", line 226, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "/home/manish/new-text-detection-ctpn/lib/fast_rcnn/train.py", line 165, in train_model
    summary_str, _ = sess.run(fetches=fetch_list, feed_dict=feed_dict)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmax of an empty sequence
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/Reshape_1, _arg_gt_boxes_0_3, _arg_gt_ishard_0_4, _arg_dontcare_areas_0_2, _arg_im_info_0_5, rpn-data/PyFunc/input_5, rpn-data/PyFunc/input_5)]]

Caused by op 'rpn-data/PyFunc', defined at:
  File "./ctpn/train_net.py", line 30, in <module>
    network = get_network('VGGnet_train')
  File "/home/manish/new-text-detection-ctpn/lib/networks/factory.py", line 10, in get_network
    return VGGnet_train()
  File "/home/manish/new-text-detection-ctpn/lib/networks/VGGnet_train.py", line 19, in __init__
    self.setup()
  File "/home/manish/new-text-detection-ctpn/lib/networks/VGGnet_train.py", line 59, in setup
    .anchor_target_layer(_feat_stride, anchor_scales, name = 'rpn-data' ))
  File "/home/manish/new-text-detection-ctpn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/manish/new-text-detection-ctpn/lib/networks/network.py", line 248, in anchor_target_layer
    [tf.float32,tf.float32,tf.float32,tf.float32])
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 212, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_script_ops.py", line 50, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/manish/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ValueError: attempt to get argmax of an empty sequence
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/Reshape_1, _arg_gt_boxes_0_3, _arg_gt_ishard_0_4, _arg_dontcare_areas_0_2, _arg_im_info_0_5, rpn-data/PyFunc/input_5, rpn-data/PyFunc/input_5)]]

**Comment by JiteshPshah** [comment]
Refer this link
https://github.com/longcw/faster_rcnn_pytorch/issues/37
