### ISSUE TITLE
Detect text with different height

### ISSUE THREAD

**Issue by guddulrk** [eragonruan/text-detection-ctpn#63]
Hi,
I have some images having the text of different heights. I have changed the base_size value to 23 then 33 in generate_anchors.py as well as in ANCHOR_SCALES: [33] in text.yml, but all those parameters have no any effect. Can you please tell me which parameters should I change?

Thanks.

**Comment by eragonruan** [comment]
@guddulrk the ANCHOR_SCALES must be fixed to 16, this is the width of proposals. for more detail, refer to the [paper[(https://arxiv.org/abs/1609.03605).

**Comment by huiyang865** [comment]
Hi,
I also have the same problem for the multi-height text detection. Some text with less height cannot be detected correctly. Which parameter should I change to meet my new needs? Can you help me?

**Comment by eragonruan** [comment]
@huiyang865 have you tried multi-scale test?
