### ISSUE TITLE
text detection in vertical Images ((text flow in vertical direction) )

### ISSUE THREAD

**Issue by JiteshPshah** [eragonruan/text-detection-ctpn#65]
Hi, is this algorithm works for vertical Images (text flow in vertical direction) and what is the meaning of Horizontally flipped Images? If it does not work for text flow vertical direction, how do I change the bounding box coordinates if I flip the Images 90 degree (text flow in horizontal direction)?

**Comment by eragonruan** [comment]
@JiteshPshah 
- the performance of this model on vertical text is not good enough.
- i flipped the image horizontally as data augment
- the gt is order in clockwise for left-top=>right-top=>right-bottom=>left-bottom

**Comment by JiteshPshah** [comment]
ohh.. so if I feed the vertical Images (text flow in vertical direction) for training , you are flipped the Images into horizontal direction right ?

**Comment by eragonruan** [comment]
yes, both the origin images and flipped images are used to train the model

**Comment by JiteshPshah** [comment]
Cool , Thanks ....

**Comment by eragonruan** [comment]
@JiteshPshah ctpn may not able to achieve good performance for vertical texts, but you can follow ctpn's idea, fix the proposals height, and predict the width. this may able to achieve good results in vertical texts
