### ISSUE TITLE
how do i prepare dataset

### ISSUE THREAD

**Issue by sneffort** [eragonruan/text-detection-ctpn#75]
i prepare two files, one is image and the other is label. the label file name is like gt_imagename.txt, and the image name is like imagename.jpg.
Then, i run split_label.py and ToVoc.py. it's ok
The question is when i run ./ctpn/train_net.py. Something wrong happened.
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 20, in <module>
    roidb = get_training_roidb(imdb)
  File "text-detection-ctpn/lib/fast_rcnn/train.py", line 194, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "text-detection-ctpn/lib/roi_data_layer/roidb.py", line 18, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range

**Comment by lovebobo** [comment]
I also meet the same problem。 Have you solved if？

**Comment by maichm** [comment]
referece https://github.com/eragonruan/text-detection-ctpn/issues/190
try delete the cache in data/
