### ISSUE TITLE
different font size text detection setting

### ISSUE THREAD

**Issue by wanghaisheng** [eragonruan/text-detection-ctpn#78]
we encounter pictures which contains different font size text,for example 
there is two lines here
```
2017-0802   font size 16
chinese-ocr-result   font size 48
```
I have tried many text_connect_cfg.py setting ,which  I can detect the lower font size text instead of the bigger one

**Comment by eragonruan** [comment]
@wanghaisheng sorry, I don't get you. did you mean that you can detect small text, but the results on big texts is poor?

**Comment by wanghaisheng** [comment]
something like that .small text in image works fine ,bigger one is poor@ eragonruan

**Comment by eragonruan** [comment]
the max anchor height is 283, so results on texts higher than this would be poor. multi-scale test may be of help

**Comment by wanghaisheng** [comment]
@eragonruan   which one should I adjust for the multi-scale test
```

    SCALE=600
    MAX_SCALE=1200
    TEXT_PROPOSALS_WIDTH=16
    MIN_NUM_PROPOSALS = 3
    MIN_RATIO=0.5
    LINE_MIN_SCORE=0.9
    MAX_HORIZONTAL_GAP=50
    TEXT_PROPOSALS_MIN_SCORE=0.7
    TEXT_PROPOSALS_NMS_THRESH=0.2
    MIN_V_OVERLAPS=0.7
    MIN_SIZE_SIM=0.7

```

**Comment by eragonruan** [comment]
scale and max_scale , but multi-scale test has not been implemented, you have to rewrite demo yourself.

**Comment by wanghaisheng** [comment]
@eragonruan by  multi-scale test    do you mean mannually set scale and max_scale to overwirte these values in configure files?

**Comment by eragonruan** [comment]
@wanghaisheng yes
