### ISSUE TITLE
Is there faster rcnn/ssd/yolo based model for text detection?

### ISSUE THREAD

**Issue by yt605155624** [eragonruan/text-detection-ctpn#90]
我觉得fast rcnn有点慢了，作者您有没有训练过更快的目标检测模型呢？有的话求分享呀，嘿嘿~

**Comment by eragonruan** [comment]
@yt605155624 这个模型就是基于faster rcnn的，但是本质上CTPN只有RPN的，没有RCNN，速度应该是足以保证的。但是basenet用的是VGG，参数比较多，可能会影响速度。
